import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    projects: [
      // ── Proyecto 1: Tests de integración (requieren DB real en puerto 5434) ──
      {
        test: {
          name: "integration",
          environment: "node",
          globalSetup: ["./test/global-setup.ts"],
          include: [
            "test/access.test.ts",
            "test/access-expiry.test.ts",
            "test/access-reviews.test.ts",
            "test/admin-cms.test.ts",
            "test/admin-portal.test.ts",
            "test/ai.test.ts",
            "test/analytics.test.ts",
            "test/audit-chain.test.ts",
            "test/auth.test.ts",
            "test/booking-changes.test.ts",
            "test/bounce.test.ts",
            "test/booking-claim.test.ts",
            "test/business-contracts.test.ts",
            "test/capability-grants.test.ts",
            "test/contact-metrics.test.ts",
            "test/business-verification.test.ts",
            "test/content.test.ts",
            "test/content-service.test.ts",
            "test/creator-campaigns.test.ts",
            "test/creators-appeals.test.ts",
            "test/discover-live.test.ts",
            "test/dual-approval.test.ts",
            "test/email-admin.test.ts",
            "test/explore.test.ts",
            "test/game.test.ts",
            "test/i18n.test.ts",
            "test/impersonation.test.ts",
            "test/imports.test.ts",
            "test/insights.test.ts",
            "test/integrity.test.ts",
            "test/jobs.test.ts",
            "test/mail-queue.test.ts",
            "test/mail-smtp.test.ts",
            "test/marketing.test.ts",
            "test/marketplace.test.ts",
            "test/media-infra.test.ts",
            "test/media.test.ts",
            "test/migrations.test.ts",
            "test/notifications.test.ts",
            "test/oauth.test.ts",
            "test/operators-b.test.ts",
            "test/operators.test.ts",
            "test/org-join-requests.test.ts",
            "test/ownership-transfer.test.ts",
            "test/payments.test.ts",
            "test/plan-batch.test.ts",
            "test/provinces-config.test.ts",
            "test/rate-limit.test.ts",
            "test/reconciliation.test.ts",
            "test/reviews.test.ts",
            "test/security.test.ts",
            "test/social-campaigns.test.ts",
            "test/staff-invitations.test.ts",
            "test/static-import.test.ts",
            "test/store.test.ts",
            "test/synthetic-data.test.ts",
            "test/system.test.ts",
            "test/tasks-per-profile.test.ts",
            "test/tools.test.ts",
            "test/trips.test.ts",
            "test/two-factor.test.ts",
            "test/user-forms.test.ts",
            "test/webhooks.test.ts",
          ],
          fileParallelism: false, // comparten la misma DB de pruebas
          testTimeout: 30_000,
          hookTimeout: 120_000,
        },
      },
      // ── Proyecto 2: Tests unitarios (mocks puros, sin DB real) ────────────
      {
        test: {
          name: "unit",
          environment: "node",
          include: [
            "test/breaker.test.ts",
            "test/cache.test.ts",
            "test/creators.test.ts",
            "test/gateways-local.test.ts",
            "test/keys.test.ts",
            "test/memberships-ticketing.test.ts",
            "test/monetization.test.ts",
            "test/operators-domain.test.ts",
            "test/request-context.test.ts",
            "test/sponsorship.test.ts",
            "test/templates.test.ts",
          ],
          fileParallelism: true,
          testTimeout: 10_000,
        },
      },
    ],
  },
});
