-- GENERADO por scripts/gen-baseline.ts — no editar a mano. Ver backend/README.md.
-- Fuentes: mysql/schema.sql (124 tablas), supabase/migrations + supabase/schema.sql, y columnas inferidas de src/integrations/supabase/mockDb.json.
-- Total: 138 tablas (0 inferidas sólo del mock; 47 columnas añadidas desde el mock).

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- achievements  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "achievements" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "description" text,
  "short_description" text,
  "icon" text NOT NULL DEFAULT '🏆',
  "xp_reward" integer DEFAULT 0,
  "coin_reward" integer DEFAULT 0,
  "category" text NOT NULL,
  "display_order" integer DEFAULT 0,
  "is_active" boolean DEFAULT TRUE,
  "season" text,
  "available_from" date,
  "available_until" date,
  "is_secret" boolean DEFAULT FALSE,
  "rarity" text DEFAULT 'common',
  "progress_max" integer DEFAULT 1,
  "total_unlocked" integer DEFAULT 0,
  "created_at" timestamptz DEFAULT now(),
  "achievement_type" text,  -- inferida de mockDb.json
  "badge_color" text,  -- inferida de mockDb.json
  "is_hidden" integer,  -- inferida de mockDb.json
  "min_level" integer,  -- inferida de mockDb.json
  "slug" text,  -- inferida de mockDb.json
  "unlock_condition" text,  -- inferida de mockDb.json
  "unlock_requirement" text,  -- inferida de mockDb.json
  "updated_at" timestamptz  -- inferida de mockDb.json
);

-- ad_banners  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "ad_banners" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text UNIQUE,
  "image_url" text,
  "alt_text" text,
  "target_url" text,
  "headline" text,
  "subtext" text,
  "cta_text" text,
  "sponsor" text,
  "banner_type" text,
  "placement" text,
  "section" text,
  "page" text,
  "start_date" date,
  "end_date" date,
  "priority" integer DEFAULT 0,
  "is_active" boolean DEFAULT TRUE,
  "is_featured" boolean DEFAULT FALSE,
  "created_at" timestamptz DEFAULT now(),
  "content_type" TEXT NOT NULL DEFAULT 'image',
  "video_url" TEXT,
  "video_autoplay" BOOLEAN DEFAULT true,
  "video_loop" BOOLEAN DEFAULT true,
  "video_muted" BOOLEAN DEFAULT true,
  "animation_type" TEXT,
  "animation_config" JSONB,
  "slider_items" JSONB,
  "slider_interval" INTEGER DEFAULT 5000
);

-- admin_activity_logs  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "admin_activity_logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_id" uuid,
  "action_type" text NOT NULL,
  "entity_name" text NOT NULL,
  "entity_id" uuid,
  "old_data" jsonb,
  "new_data" jsonb,
  "created_at" timestamptz DEFAULT now()
);

-- airbnb_listings  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "airbnb_listings" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "property_type" text,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "address" text,
  "guests" integer,
  "bedrooms" integer,
  "beds" integer,
  "bathrooms" integer,
  "price_per_night" numeric(10,2),
  "cleaning_fee" numeric(10,2) DEFAULT 0.00,
  "service_fee" numeric(10,2) DEFAULT 0.00,
  "amenities" jsonb,
  "house_rules" jsonb,
  "check_in_time" text,
  "check_out_time" text,
  "cancellation_policy" text,
  "host_name" text,
  "host_image" text,
  "host_description" text,
  "is_superhost" boolean DEFAULT FALSE,
  "min_nights" integer DEFAULT 1,
  "max_nights" integer DEFAULT 1125,
  "instant_book" boolean DEFAULT FALSE,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "rating" numeric(3,2) DEFAULT 0.00,
  "is_featured" boolean DEFAULT FALSE,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now(),
  "is_sponsored" boolean DEFAULT false,
  "review_count" integer,  -- inferida de mockDb.json
  "updated_at" timestamptz  -- inferida de mockDb.json
);

-- ambassador_payouts  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "ambassador_payouts" (
  "id" uuid PRIMARY KEY,
  "ambassador_id" uuid NOT NULL,
  "amount" numeric(10,2) NOT NULL,
  "status" text DEFAULT 'pending',
  "payout_method" text NOT NULL,
  "payout_details" text,
  "processed_at" timestamptz,
  "created_at" timestamptz DEFAULT now()
);

-- ambassador_referrals  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "ambassador_referrals" (
  "id" uuid PRIMARY KEY,
  "ambassador_id" uuid NOT NULL,
  "referred_email" text NOT NULL,
  "sale_amount" numeric(10,2) NOT NULL,
  "commission_earned" numeric(10,2) NOT NULL,
  "status" text DEFAULT 'pending',
  "created_at" timestamptz DEFAULT now()
);

-- ambassadors  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "ambassadors" (
  "id" uuid PRIMARY KEY,
  "referral_code" text NOT NULL UNIQUE,
  "sales_count" integer DEFAULT 0,
  "total_earned" numeric(12,2) DEFAULT 0.00,
  "pending_payout" numeric(12,2) DEFAULT 0.00,
  "tier" text DEFAULT 'bronze',
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now()
);

-- analytics_events  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "analytics_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "event_type" text NOT NULL,
  "page" text,
  "session_id" text,
  "metadata" jsonb,
  "created_at" timestamptz DEFAULT now()
);

-- article_translations  (supabase/migrations/20260307)
CREATE TABLE IF NOT EXISTS "article_translations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "article_id" uuid NOT NULL,
  "locale" text NOT NULL,
  "title" text NOT NULL,
  "excerpt" text,
  "content" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE(article_id, locale)
);

-- articles  (supabase/migrations/20260307)
CREATE TABLE IF NOT EXISTS "articles" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "slug" text UNIQUE,
  "title" text NOT NULL,
  "excerpt" text,
  "content" text,
  "image_url" text,
  "gallery" text[],
  "category" text DEFAULT 'general',
  "tags" text[] DEFAULT '{}',
  "author_name" text,
  "author_image" text,
  "is_published" boolean DEFAULT false,
  "is_featured" boolean DEFAULT false,
  "published_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- artisanal_workshops  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "artisanal_workshops" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "destination_id" uuid,
  "workshop_type" text,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "address" text,
  "phone" text,
  "email" text,
  "website" text,
  "craft_types" jsonb,
  "duration" text,
  "price_range" text,
  "includes" jsonb,
  "skill_level" text,
  "languages" jsonb,
  "max_participants" integer,
  "opening_hours" text,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "rating" numeric(3,2) DEFAULT 0.00,
  "review_count" integer DEFAULT 0,
  "is_featured" boolean DEFAULT FALSE,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- audio_guides  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "audio_guides" (
  "id" uuid PRIMARY KEY,
  "title" text NOT NULL,
  "description" text,
  "audio_url" text NOT NULL,
  "language" text DEFAULT 'es',
  "associated_entity_type" text NOT NULL,
  "associated_entity_id" uuid NOT NULL,
  "duration_seconds" integer
);

-- bars  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "bars" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "bar_type" jsonb,
  "price_range" text,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "address" text,
  "phone" text,
  "opening_hours" jsonb,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "rating" numeric(3,2) DEFAULT 0.00,
  "is_featured" boolean DEFAULT FALSE,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now(),
  "is_sponsored" boolean DEFAULT false,
  "ambiance" text,  -- inferida de mockDb.json
  "dress_code" text,  -- inferida de mockDb.json
  "email" text,  -- inferida de mockDb.json
  "minimum_age" integer,  -- inferida de mockDb.json
  "music_style" text,  -- inferida de mockDb.json
  "review_count" integer,  -- inferida de mockDb.json
  "services" jsonb,  -- inferida de mockDb.json
  "updated_at" timestamptz,  -- inferida de mockDb.json
  "website" text  -- inferida de mockDb.json
);

-- beaches  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "beaches" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "destination_id" uuid,
  "province_id" uuid,
  "name" text NOT NULL,
  "slug" text UNIQUE,
  "beach_type" text,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "activities" jsonb,
  "amenities" jsonb,
  "water_color" text,
  "sand_type" text,
  "wave_intensity" text,
  "crowd_level" text,
  "access_type" text,
  "parking_available" boolean DEFAULT FALSE,
  "lifeguard_on_duty" boolean DEFAULT FALSE,
  "how_to_get_there" text,
  "best_time_to_visit" text,
  "address" text,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "rating" numeric(3,2) DEFAULT 0.00,
  "review_count" integer DEFAULT 0,
  "is_popular" boolean DEFAULT FALSE,
  "is_featured" boolean DEFAULT FALSE,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- bird_species  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "bird_species" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "scientific_name" text NOT NULL,
  "status" text NOT NULL CHECK ("status" IN ('Endémica', 'Residente', 'Migratoria')),
  "conservation" text NOT NULL CHECK ("conservation" IN ('Preocupación Menor', 'Vulnerable', 'En Peligro Crítico')),
  "description" text NOT NULL,
  "best_locations" jsonb NOT NULL,
  "avatar" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- blog_posts  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "blog_posts" (
  "id" uuid PRIMARY KEY,
  "title" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "content" text NOT NULL,
  "summary" text,
  "image_url" text,
  "author_id" uuid,
  "category" text,
  "published_at" timestamptz,
  "is_featured" boolean DEFAULT FALSE,
  "created_at" timestamptz DEFAULT now()
);

-- cart_items  (supabase/migrations/20260308)
CREATE TABLE IF NOT EXISTS "cart_items" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" UUID NOT NULL,
  "product_id" TEXT NOT NULL,
  "product_name" TEXT NOT NULL,
  "product_image" TEXT,
  "price" NUMERIC NOT NULL DEFAULT 0,
  "quantity" INTEGER NOT NULL DEFAULT 1,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- caves  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "caves" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "cave_type" text,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "address" text,
  "phone" text,
  "email" text,
  "website" text,
  "difficulty" text,
  "tour_duration" text,
  "opening_hours" text,
  "highlights" jsonb,
  "flora_fauna" jsonb,
  "historical_info" text,
  "price_adult" numeric(10,2),
  "price_child" numeric(10,2),
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "rating" numeric(3,2) DEFAULT 0.00,
  "is_featured" boolean DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- clinics  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "clinics" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "address" text,
  "phone" text,
  "email" text,
  "website" text,
  "specialties" jsonb,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now()
);

-- coffee_experiences  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "coffee_experiences" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "experience_type" text,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "address" text,
  "phone" text,
  "email" text,
  "website" text,
  "coffee_varieties" jsonb,
  "altitude" text,
  "tour_duration" text,
  "price_range" text,
  "includes" jsonb,
  "production_process" text,
  "tasting_notes" jsonb,
  "opening_hours" text,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "rating" numeric(3,2) DEFAULT 0.00,
  "is_featured" boolean DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- contest_registrations  (supabase/migrations/20260307)
CREATE TABLE IF NOT EXISTS "contest_registrations" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  "nombre" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "telefono" TEXT,
  "pais" TEXT,
  "edad" TEXT,
  "visitado" TEXT,
  "intereses" TEXT[],
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- destinations  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "destinations" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "province_id" uuid,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "highlights" jsonb,
  "typical_dishes" jsonb,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "weather_info" text,
  "best_time_to_visit" text,
  "how_to_get_there" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "deleted_at" TIMESTAMPTZ DEFAULT NULL
);

-- digital_collectibles  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "digital_collectibles" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text UNIQUE,
  "description" text,
  "short_description" text,
  "collectible_type" text NOT NULL,
  "rarity" text NOT NULL DEFAULT 'common',
  "image_url" text,
  "animated_url" text,
  "thumbnail_url" text,
  "unlock_condition" text,
  "unlock_requirement" jsonb,
  "total_supply" integer,
  "current_supply" integer DEFAULT 0,
  "xp_value" integer DEFAULT 0,
  "coin_value" integer DEFAULT 0,
  "is_tradeable" boolean DEFAULT FALSE,
  "is_active" boolean DEFAULT TRUE,
  "season" text,
  "event_id" uuid,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- discount_coupons  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "discount_coupons" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "code" text NOT NULL UNIQUE,
  "discount_percentage" numeric(5,2),
  "discount_amount" numeric(10,2),
  "expires_at" timestamptz,
  "max_uses" integer,
  "uses_count" integer DEFAULT 0,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- emergency_contacts  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "emergency_contacts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "province_id" uuid,
  "institution" text NOT NULL,
  "phone_number" text NOT NULL,
  "address" text,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- entity_translations  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "entity_translations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "entity_type" text NOT NULL,
  "entity_id" uuid NOT NULL,
  "language" text NOT NULL,
  "field_name" text NOT NULL,
  "translation_text" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("entity_type", "entity_id", "language", "field_name")
);

-- establecimientos  (supabase/migrations/20260308)
CREATE TABLE IF NOT EXISTS "establecimientos" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  "subsector" text NOT NULL,
  "actividad" text,
  "rut" text,
  "numero_identificacion" text,
  "nombre" text NOT NULL,
  "sector_zona" text,
  "provincia" text,
  "estatus_proceso" text,
  "estatus_licencia" text,
  "estatus_establecimiento" text,
  "fecha_vencimiento" date,
  "telefono" text,
  "correo" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);

-- establishment_registrations  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "establishment_registrations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tipo_establecimiento" text NOT NULL CHECK (tipo_establecimiento IN ('general', 'restaurante', 'bar', 'hotel', 'tour', 'spa', 'tienda')),
  "nombre" text NOT NULL,
  "responsable" text NOT NULL,
  "email" text NOT NULL,
  "telefono" text NOT NULL,
  "direccion" text NOT NULL,
  "provincia" text NOT NULL,
  "website" text,
  "foto_url" text,
  "descripcion" text NOT NULL,
  "rnc" text,
  "horario" text,
  "detalles" jsonb,
  "status" text DEFAULT 'pendiente' CHECK (status IN ('pendiente', 'aprobado', 'rechazado')),
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- event_tickets  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "event_tickets" (
  "id" uuid PRIMARY KEY,
  "reservation_id" uuid,
  "ticket_code" text NOT NULL UNIQUE,
  "status" text DEFAULT 'unused' CHECK ("status" IN ('unused', 'scanned', 'cancelled')),
  "scanned_at" timestamptz,
  "created_at" timestamptz DEFAULT now()
);

-- events  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "events" (
  "id" uuid PRIMARY KEY,
  "title" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "start_date" date NOT NULL,
  "end_date" date,
  "location" text,
  "description" text,
  "image_url" text,
  "category" text,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now()
);

-- exchange_rates  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "exchange_rates" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "rate_date" date NOT NULL,
  "currency_code" text NOT NULL CHECK (currency_code IN ('USD', 'EUR', 'GBP', 'CAD', 'MXN')),
  "buy_rate" numeric(10,4) NOT NULL,
  "sell_rate" numeric(10,4) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("rate_date", "currency_code")
);

-- experiences  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "experiences" (
  "id" uuid PRIMARY KEY,
  "title" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "category" text NOT NULL,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "duration" text,
  "price" numeric(10,2),
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now(),
  "is_sponsored" boolean DEFAULT false,
  "best_season" text,  -- inferida de mockDb.json
  "difficulty" text,  -- inferida de mockDb.json
  "experience_type" text,  -- inferida de mockDb.json
  "highlights" jsonb,  -- inferida de mockDb.json
  "included" jsonb,  -- inferida de mockDb.json
  "is_featured" integer,  -- inferida de mockDb.json
  "name" text,  -- inferida de mockDb.json
  "price_range" text,  -- inferida de mockDb.json
  "rating" text,  -- inferida de mockDb.json
  "requirements" jsonb,  -- inferida de mockDb.json
  "updated_at" timestamptz,  -- inferida de mockDb.json
  "review_count" integer  -- inferida de mockDb.json
);

-- explorer_follows  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "explorer_follows" (
  "id" uuid PRIMARY KEY,
  "follower_id" uuid NOT NULL,
  "following_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  UNIQUE ("follower_id", "following_id")
);

-- explorer_guilds  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "explorer_guilds" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "description" text,
  "icon" text NOT NULL DEFAULT '🏴',
  "region" text NOT NULL,
  "member_count" integer NOT NULL DEFAULT 0,
  "total_xp" bigint NOT NULL DEFAULT 0,
  "is_official" boolean NOT NULL DEFAULT FALSE,
  "created_by" uuid,
  "created_at" timestamptz DEFAULT now()
);

-- favorites  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "favorites" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  UNIQUE ("user_id", "entity_type", "entity_id")
);

-- fuel_prices  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "fuel_prices" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "effective_date" date NOT NULL UNIQUE,
  "gasolina_premium" numeric(10,2) NOT NULL,
  "gasolina_regular" numeric(10,2) NOT NULL,
  "gasoil_optimo" numeric(10,2) NOT NULL,
  "gasoil_regular" numeric(10,2) NOT NULL,
  "glp" numeric(10,2) NOT NULL,
  "gnv" numeric(10,2) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- gamification_leagues  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "gamification_leagues" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "icon" text NOT NULL DEFAULT '🏅',
  "min_xp_week" integer NOT NULL DEFAULT 0,
  "max_xp_week" integer,
  "color" text NOT NULL DEFAULT '#6B7280',
  "bg_color" text NOT NULL DEFAULT '#F3F4F6',
  "coin_reward" integer NOT NULL DEFAULT 0,
  "display_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamptz DEFAULT now()
);

-- gamification_levels  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "gamification_levels" (
  "id" uuid PRIMARY KEY,
  "level_number" integer NOT NULL UNIQUE,
  "title" text NOT NULL,
  "xp_required" integer NOT NULL,
  "icon" text NOT NULL DEFAULT '🌱',
  "color" text NOT NULL DEFAULT '#8B5CF6',
  "marketplace_discount" integer DEFAULT 0,
  "perks" jsonb,
  "created_at" timestamptz DEFAULT now()
);

-- gamification_missions  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "gamification_missions" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "description" text,
  "target_action" text NOT NULL,
  "target_count" integer NOT NULL DEFAULT 1,
  "xp_reward" integer NOT NULL DEFAULT 0,
  "coin_reward" integer NOT NULL DEFAULT 0,
  "mission_type" text NOT NULL DEFAULT 'daily' CHECK ("mission_type" IN ('daily', 'weekly', 'story', 'onboarding')),
  "is_featured" boolean DEFAULT FALSE,
  "is_active" boolean DEFAULT TRUE,
  "min_level" integer DEFAULT 1,
  "icon" text DEFAULT '🎯',
  "created_at" timestamptz DEFAULT now()
);

-- gamification_prizes  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "gamification_prizes" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "description" text,
  "short_description" text,
  "image_url" text,
  "prize_type" text NOT NULL DEFAULT 'experience',
  "coin_cost" integer NOT NULL DEFAULT 100,
  "min_level" integer DEFAULT 1,
  "quantity_available" integer,
  "quantity_redeemed" integer DEFAULT 0,
  "is_active" boolean DEFAULT TRUE,
  "is_featured" boolean DEFAULT FALSE,
  "sponsor" text,
  "valid_until" date,
  "terms" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- gamification_seasons  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "gamification_seasons" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "number" integer NOT NULL,
  "starts_at" timestamptz NOT NULL,
  "ends_at" timestamptz NOT NULL,
  "is_active" boolean NOT NULL DEFAULT FALSE,
  "top_rewards" jsonb,
  "created_at" timestamptz DEFAULT now()
);

-- gamification_transactions  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "gamification_transactions" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "transaction_type" text NOT NULL,
  "xp_amount" integer DEFAULT 0,
  "coin_amount" integer DEFAULT 0,
  "description" text,
  "source_type" text,
  "source_id" text,
  "created_at" timestamptz DEFAULT now()
);

-- gamified_routes  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "gamified_routes" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text UNIQUE,
  "description" text,
  "short_description" text,
  "route_type" text NOT NULL DEFAULT 'adventure',
  "difficulty" text,
  "duration_days" integer,
  "distance_km" numeric(12,2),
  "total_xp_reward" integer DEFAULT 0,
  "total_coin_reward" integer DEFAULT 0,
  "completion_badge_id" uuid,
  "image_url" text,
  "gallery" jsonb,
  "min_level" integer DEFAULT 1,
  "is_featured" boolean DEFAULT FALSE,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- golf_courses  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "golf_courses" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "holes" integer NOT NULL,
  "par" integer NOT NULL,
  "designer" text,
  "description" text,
  "image_url" text,
  "created_at" timestamptz DEFAULT now()
);

-- guild_members  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "guild_members" (
  "id" uuid PRIMARY KEY,
  "guild_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "role" text NOT NULL DEFAULT 'member',
  "joined_at" timestamptz DEFAULT now(),
  UNIQUE ("guild_id", "user_id")
);

-- historical_events  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "historical_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "event_date" date,
  "end_date" date,
  "year" integer,
  "era" text,
  "category" text,
  "location" text,
  "short_description" text,
  "description" text,
  "significance" text,
  "key_figures" jsonb,
  "consequences" jsonb,
  "image_url" text,
  "gallery" jsonb,
  "sources" jsonb,
  "is_featured" boolean DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- historical_figures  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "historical_figures" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "title" text,
  "birth_date" date,
  "death_date" date,
  "birth_place" text,
  "era" text,
  "category" text,
  "short_description" text,
  "description" text,
  "biography" text,
  "achievements" jsonb,
  "quotes" jsonb,
  "image_url" text,
  "gallery" jsonb,
  "is_featured" boolean DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- hot_springs  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "hot_springs" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "location" text NOT NULL,
  "province" text NOT NULL,
  "temp_celsius" numeric(4,1) NOT NULL,
  "properties" jsonb NOT NULL,
  "description" text NOT NULL,
  "access" text NOT NULL CHECK ("access" IN ('Fácil', 'Moderado', 'Aventura (Difícil)')),
  "price" text NOT NULL,
  "avatar" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- hotels  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "hotels" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "category" text,
  "stars" integer CHECK ("stars" BETWEEN 1 AND 5),
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "address" text,
  "phone" text,
  "email" text,
  "website" text,
  "price_range" text,
  "amenities" jsonb,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "rating" numeric(3,2) DEFAULT 0.00,
  "is_featured" boolean DEFAULT FALSE,
  "is_sponsored" boolean DEFAULT FALSE,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "deleted_at" TIMESTAMPTZ DEFAULT NULL,
  "review_count" integer  -- inferida de mockDb.json
);

-- ip_rules  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "ip_rules" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "ip_address" text NOT NULL UNIQUE,
  "rule_type" text CHECK (rule_type IN ('blacklist', 'whitelist')),
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- job_vacancies  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "job_vacancies" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "company_name" text NOT NULL,
  "company_logo" text,
  "company_description" text,
  "description" text,
  "short_description" text,
  "location" text,
  "address" text,
  "province" text,
  "salary_range" text,
  "salary_min" numeric(10,2),
  "salary_max" numeric(10,2),
  "job_type" text,
  "experience_level" text,
  "education" text,
  "category" text,
  "department" text,
  "languages" jsonb,
  "responsibilities" jsonb,
  "requirements" jsonb,
  "benefits" jsonb,
  "skills" jsonb,
  "application_url" text,
  "application_email" text,
  "deadline" date,
  "is_urgent" boolean DEFAULT FALSE,
  "is_remote" boolean DEFAULT FALSE,
  "is_featured" boolean DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- lotteries  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "lotteries" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "country" text NOT NULL DEFAULT 'República Dominicana',
  "logo_url" text,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- lottery_draws  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "lottery_draws" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "lottery_id" uuid,
  "name" text NOT NULL,
  "draw_days" jsonb NOT NULL,
  "draw_time" time NOT NULL,
  "ball_range_min" integer DEFAULT 1,
  "ball_range_max" integer DEFAULT 100,
  "number_of_balls" integer DEFAULT 3,
  "tombolas_count" integer DEFAULT 3,
  "has_bonus" boolean DEFAULT FALSE,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- lottery_results  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "lottery_results" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "draw_id" uuid,
  "draw_date" date NOT NULL,
  "winning_numbers" jsonb NOT NULL,
  "bonus_number" integer,
  "jackpot_amount" text,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("draw_id", "draw_date")
);

-- marine_reports  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "marine_reports" (
  "id" uuid PRIMARY KEY,
  "location" text NOT NULL,
  "wind_speed" numeric(4,1) NOT NULL,
  "wind_direction" text NOT NULL,
  "wave_height" numeric(3,1) NOT NULL,
  "wave_period" integer NOT NULL,
  "water_temp" numeric(3,1) NOT NULL,
  "condition_rating" text NOT NULL CHECK ("condition_rating" IN ('Excelente', 'Buena', 'Regular', 'Mala')),
  "recommendation" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- marketing_campaigns  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "marketing_campaigns" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "title" text NOT NULL,
  "subject" text NOT NULL,
  "body_template" text NOT NULL,
  "segment_interests" jsonb,
  "sent_count" integer DEFAULT 0,
  "status" text DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'sending', 'sent', 'failed')),
  "scheduled_for" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- marketing_leads  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "marketing_leads" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "nombre" text NOT NULL,
  "email" text NOT NULL,
  "telefono" text,
  "empresa" text,
  "mensaje" text,
  "source" text,
  "status" text DEFAULT 'nuevo' CHECK (status IN ('nuevo', 'contactado', 'calificado', 'perdido')),
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- marketplace_order_items  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "marketplace_order_items" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "order_id" uuid,
  "item_type" text CHECK (item_type IN ('experience', 'tour_package', 'ticket')),
  "item_id" uuid NOT NULL,
  "quantity" integer NOT NULL DEFAULT 1,
  "price_unit" numeric(10,2) NOT NULL
);

-- marketplace_orders  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "marketplace_orders" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid,
  "total_amount" numeric(10,2) NOT NULL,
  "status" text DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'cancelled', 'refunded')),
  "payment_method" text,
  "payment_intent_id" text,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- monuments  (supabase/migrations/20260309)
CREATE TABLE IF NOT EXISTS "monuments" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" TEXT NOT NULL,
  "slug" TEXT UNIQUE,
  "monument_type" TEXT DEFAULT 'monumento',
  "description" TEXT,
  "short_description" TEXT,
  "historical_period" TEXT,
  "year_built" TEXT,
  "architect" TEXT,
  "address" TEXT,
  "province_id" UUID,
  "destination_id" UUID,
  "latitude" NUMERIC,
  "longitude" NUMERIC,
  "image_url" TEXT,
  "gallery" TEXT[],
  "opening_hours" TEXT,
  "entry_fee" TEXT,
  "phone" TEXT,
  "website" TEXT,
  "rating" NUMERIC DEFAULT 4.0,
  "review_count" INTEGER DEFAULT 0,
  "is_featured" BOOLEAN DEFAULT false,
  "is_active" BOOLEAN DEFAULT true,
  "highlights" TEXT[],
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now()
);

-- municipalities  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "municipalities" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "province_id" uuid NOT NULL,
  "municipality_type" text,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "highlights" jsonb,
  "population" integer,
  "area_km2" numeric(10,2),
  "is_tourist_destination" boolean DEFAULT FALSE,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "created_at" timestamptz DEFAULT now()
);

-- newsletter_subscribers  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "newsletter_subscribers" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "email" text NOT NULL UNIQUE,
  "nombre" text,
  "intereses" jsonb,
  "frecuencia" text DEFAULT 'biweekly',
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- notifications  (supabase/migrations/20260308)
CREATE TABLE IF NOT EXISTS "notifications" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" UUID NOT NULL,
  "title" TEXT NOT NULL,
  "message" TEXT,
  "type" TEXT NOT NULL DEFAULT 'info',
  "link" TEXT,
  "is_read" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- offers  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "offers" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "title" text NOT NULL,
  "description" text,
  "discount_code" text,
  "discount_percentage" numeric(12,2),
  "original_price" numeric(12,2) NOT NULL,
  "price" numeric(12,2) NOT NULL,
  "start_time" timestamptz,
  "end_time" timestamptz,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "radius_meters" integer DEFAULT 500,
  "is_flash" boolean DEFAULT FALSE,
  "image_url" text,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- offset_projects  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "offset_projects" (
  "id" uuid PRIMARY KEY,
  "title" text NOT NULL,
  "location" text NOT NULL,
  "category" text NOT NULL,
  "description" text NOT NULL,
  "cost_info" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- operator_listings  (supabase/migrations/20260924)
CREATE TABLE IF NOT EXISTS "operator_listings" (
  "id" text PRIMARY KEY,
  "org_id" uuid NOT NULL,
  "category" text NOT NULL CHECK (category IN ('experiencia','voluntariado','alojamiento','transporte')),
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "summary" text NOT NULL DEFAULT '',
  "description" text NOT NULL DEFAULT '',
  "destination" text,
  "price" numeric(12,2) NOT NULL CHECK (price >= 0),
  "currency" text NOT NULL DEFAULT 'USD' CHECK (currency IN ('USD','DOP')),
  "duration" text,
  "capacity" integer NOT NULL DEFAULT 1 CHECK (capacity >= 1),
  "min_age" integer DEFAULT 0,
  "languages" text[] NOT NULL DEFAULT '{}',
  "includes" text[] NOT NULL DEFAULT '{}',
  "meeting_point" text,
  "cancellation_policy" text NOT NULL DEFAULT 'flexible' CHECK (cancellation_policy IN ('flexible','moderada','estricta')),
  "images" text[] NOT NULL DEFAULT '{}',
  "time_slots" text[] NOT NULL DEFAULT '{}',
  "status" text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','paused')),
  "rating" numeric(2,1),
  "reviews_count" integer NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "rooms" jsonb,  -- inferida de mockDb.json
  "deposit_percent" integer,  -- inferida de mockDb.json
  "extras" jsonb,  -- inferida de mockDb.json
  "child_price" integer,  -- inferida de mockDb.json
  "infants_free" boolean,  -- inferida de mockDb.json
  "min_guests" integer,  -- inferida de mockDb.json
  "days" integer,  -- inferida de mockDb.json
  "itinerary" jsonb,  -- inferida de mockDb.json
  "components" jsonb,  -- inferida de mockDb.json
  UNIQUE (org_id, slug)
);

-- operator_messages  (supabase/migrations/20260924)
CREATE TABLE IF NOT EXISTS "operator_messages" (
  "id" text PRIMARY KEY,
  "org_id" uuid NOT NULL,
  "thread_id" text NOT NULL,
  "traveler_name" text NOT NULL,
  "sender" text NOT NULL CHECK (sender IN ('traveler','operator')),
  "channel" text NOT NULL CHECK (channel IN ('web','whatsapp','instagram','email')),
  "body" text NOT NULL,
  "booking_id" text,
  "read" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- operator_promotions  (supabase/migrations/20260924)
CREATE TABLE IF NOT EXISTS "operator_promotions" (
  "id" text PRIMARY KEY,
  "org_id" uuid NOT NULL,
  "code" text NOT NULL,
  "type" text NOT NULL CHECK (type IN ('percent','fixed')),
  "value" numeric(10,2) NOT NULL CHECK (value > 0),
  "listing_id" text,
  "starts_at" date,
  "ends_at" date,
  "max_uses" integer,
  "uses" integer NOT NULL DEFAULT 0,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, code)
);

-- operator_reviews  (supabase/migrations/20260924)
CREATE TABLE IF NOT EXISTS "operator_reviews" (
  "id" text PRIMARY KEY,
  "org_id" uuid NOT NULL,
  "listing_id" text,
  "author" text NOT NULL,
  "rating" integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
  "comment" text,
  "reply" text,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- parks  (supabase/migrations/20260309)
CREATE TABLE IF NOT EXISTS "parks" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" TEXT NOT NULL,
  "slug" TEXT UNIQUE,
  "park_type" TEXT DEFAULT 'parque nacional',
  "description" TEXT,
  "short_description" TEXT,
  "area_km2" NUMERIC,
  "established_year" INTEGER,
  "ecosystems" TEXT[],
  "flora_fauna" TEXT[],
  "activities" TEXT[],
  "trails" TEXT[],
  "address" TEXT,
  "province_id" UUID,
  "destination_id" UUID,
  "latitude" NUMERIC,
  "longitude" NUMERIC,
  "image_url" TEXT,
  "gallery" TEXT[],
  "opening_hours" TEXT,
  "entry_fee" TEXT,
  "phone" TEXT,
  "website" TEXT,
  "rating" NUMERIC DEFAULT 4.0,
  "review_count" INTEGER DEFAULT 0,
  "is_featured" BOOLEAN DEFAULT false,
  "is_active" BOOLEAN DEFAULT true,
  "highlights" TEXT[],
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now()
);

-- partner_profiles  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "partner_profiles" (
  "id" uuid PRIMARY KEY,
  "business_name" text NOT NULL,
  "business_type" text NOT NULL CHECK ("business_type" IN ('hotel', 'restaurant', 'bar', 'tour', 'spa', 'shop', 'operador', 'agencia', 'guia')),
  "phone" text,
  "email" text NOT NULL,
  "description" text,
  "rating" numeric(3,2) DEFAULT 5.00,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "slug" text UNIQUE,
  "verification" text NOT NULL DEFAULT 'unverified' CHECK (verification IN ('unverified','pending','verified','rejected')),
  "commission_rate" numeric(5,2) NOT NULL DEFAULT 8,
  "payout_method" text,
  "website_enabled" boolean NOT NULL DEFAULT false,
  "logo_url" text,
  "cover_url" text,
  "province" text
);

-- passport_stamps  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "passport_stamps" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL,
  "destination_id" uuid,
  "beach_id" uuid,
  "hotel_id" uuid,
  "restaurant_id" uuid,
  "experience_id" uuid,
  "stamp_type" text NOT NULL,
  "stamp_name" text NOT NULL,
  "stamp_location" text,
  "stamp_image" text,
  "visited_at" timestamptz NOT NULL DEFAULT now(),
  "verification_method" text,
  "verification_data" jsonb,
  "xp_earned" integer DEFAULT 0,
  "coins_earned" integer DEFAULT 0,
  "notes" text,
  "photos" jsonb,
  "rating" integer,
  "is_verified" boolean DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- photo_challenges  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "photo_challenges" (
  "id" uuid PRIMARY KEY,
  "title" text NOT NULL,
  "description" text,
  "theme" text NOT NULL,
  "destination" text,
  "starts_at" timestamptz DEFAULT now(),
  "ends_at" timestamptz,
  "xp_reward" integer NOT NULL DEFAULT 100,
  "coin_reward" integer NOT NULL DEFAULT 50,
  "is_active" boolean NOT NULL DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now()
);

-- photo_submissions  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "photo_submissions" (
  "id" uuid PRIMARY KEY,
  "challenge_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "image_url" text NOT NULL,
  "caption" text,
  "votes" integer NOT NULL DEFAULT 0,
  "is_approved" boolean NOT NULL DEFAULT FALSE,
  "is_winner" boolean NOT NULL DEFAULT FALSE,
  "created_at" timestamptz DEFAULT now(),
  UNIQUE ("challenge_id", "user_id")
);

-- photo_votes  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "photo_votes" (
  "id" uuid PRIMARY KEY,
  "submission_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  UNIQUE ("submission_id", "user_id")
);

-- points_transactions  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "points_transactions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid,
  "transaction_type" text CHECK (transaction_type IN ('earn_coins', 'spend_coins', 'earn_xp')),
  "amount" integer NOT NULL,
  "reason" text NOT NULL,
  "reference_entity_type" text,
  "reference_entity_id" uuid,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- ports_marinas  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "ports_marinas" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "port_type" text NOT NULL CHECK ("port_type" IN ('port', 'marina', 'both')),
  "description" text,
  "image_url" text,
  "capacity_slips" integer,
  "max_draft_feet" numeric(5,2),
  "services" jsonb,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "created_at" timestamptz DEFAULT now()
);

-- post_comments  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "post_comments" (
  "id" uuid PRIMARY KEY,
  "post_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "content" text NOT NULL CHECK (CHAR_LENGTH("content") BETWEEN 3 AND 500),
  "created_at" timestamptz DEFAULT now()
);

-- post_likes  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "post_likes" (
  "id" uuid PRIMARY KEY,
  "post_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  UNIQUE ("post_id", "user_id")
);

-- profiles  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "profiles" (
  "id" uuid PRIMARY KEY,
  "display_name" text,
  "avatar_url" text,
  "bio" text,
  "role" text DEFAULT 'user',
  "is_suspended" boolean DEFAULT FALSE,
  "suspension_reason" text,
  "travel_interests" jsonb,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- protected_areas  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "protected_areas" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text UNIQUE,
  "category" text NOT NULL CHECK ("category" IN ('Parque Nacional', 'Santuario', 'Reserva Científica')),
  "location" text NOT NULL,
  "size" text NOT NULL,
  "fee" text NOT NULL,
  "hours" text NOT NULL,
  "attractions" jsonb NOT NULL,
  "rules" jsonb NOT NULL,
  "description" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- province_visits  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "province_visits" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "province" text NOT NULL,
  "visited_at" timestamptz DEFAULT now(),
  UNIQUE ("user_id", "province")
);

-- provinces  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "provinces" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL UNIQUE,
  "region" text,
  "description" text,
  "image_url" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- referral_codes  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "referral_codes" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL UNIQUE,
  "code" text NOT NULL UNIQUE,
  "total_referrals" integer DEFAULT 0,
  "total_earnings_coins" integer DEFAULT 0,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now()
);

-- referral_uses  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "referral_uses" (
  "id" uuid PRIMARY KEY,
  "referral_code_id" uuid NOT NULL,
  "referred_user_id" uuid NOT NULL UNIQUE,
  "xp_awarded" integer DEFAULT 0,
  "coins_awarded" integer DEFAULT 0,
  "created_at" timestamptz DEFAULT now()
);

-- reservations  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "reservations" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "partner_id" uuid NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" uuid NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date,
  "total_price" numeric(10,2) DEFAULT 0.00,
  "status" text DEFAULT 'pending',
  "contact_name" text NOT NULL,
  "contact_phone" text,
  "contact_email" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "org_id" uuid REFERENCES partner_profiles(id),
  "listing_id" text REFERENCES operator_listings(id),
  "listing_title" text,
  "date" date,
  "time" text,
  "guests" integer NOT NULL DEFAULT 1,
  "currency" text NOT NULL DEFAULT 'USD',
  "payment_status" text NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid','partial','paid','refunded')),
  "promo_code" text,
  "source" text NOT NULL DEFAULT 'web' CHECK (source IN ('web','manual','marketplace')),
  "review_pending" boolean NOT NULL DEFAULT false
);

-- restaurants  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "restaurants" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "cuisine_type" jsonb,
  "price_range" text,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "address" text,
  "phone" text,
  "website" text,
  "opening_hours" jsonb,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "rating" numeric(3,2) DEFAULT 0.00,
  "is_featured" boolean DEFAULT FALSE,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now(),
  "is_sponsored" boolean DEFAULT false,
  "deleted_at" TIMESTAMPTZ DEFAULT NULL,
  "category" text,  -- inferida de mockDb.json
  "email" text,  -- inferida de mockDb.json
  "services" jsonb,  -- inferida de mockDb.json
  "signature_dishes" jsonb,  -- inferida de mockDb.json
  "updated_at" timestamptz,  -- inferida de mockDb.json
  "review_count" integer  -- inferida de mockDb.json
);

-- reviews  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "reviews" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" uuid NOT NULL,
  "rating" integer NOT NULL CHECK ("rating" BETWEEN 1 AND 5),
  "comment" text,
  "is_approved" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now()
);

-- reward_inventory  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "reward_inventory" (
  "id" uuid PRIMARY KEY,
  "title" text NOT NULL,
  "description" text,
  "coins_cost" integer NOT NULL,
  "stock" integer DEFAULT 0,
  "is_physical" boolean DEFAULT FALSE,
  "image_url" text,
  "created_at" timestamptz DEFAULT now()
);

-- reward_shipments  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "reward_shipments" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "reward_id" uuid,
  "recipient_name" text NOT NULL,
  "recipient_phone" text NOT NULL,
  "shipping_address" text NOT NULL,
  "courier_name" text,
  "tracking_number" text,
  "status" text DEFAULT 'pending' CHECK ("status" IN ('pending', 'shipped', 'delivered', 'cancelled')),
  "shipped_at" timestamptz,
  "created_at" timestamptz DEFAULT now()
);

-- rivers  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "rivers" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "address" text,
  "difficulty" text,
  "activities" jsonb,
  "best_season" text,
  "duration" text,
  "price_range" text,
  "safety_tips" jsonb,
  "adrenaline_level" integer,
  "certified_guides" boolean DEFAULT FALSE,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "rating" numeric(3,2) DEFAULT 0.00,
  "is_featured" boolean DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- route_checkpoints  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "route_checkpoints" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "route_id" uuid NOT NULL,
  "checkpoint_order" integer NOT NULL,
  "checkpoint_name" text NOT NULL,
  "checkpoint_description" text,
  "checkpoint_type" text NOT NULL,
  "destination_id" uuid,
  "beach_id" uuid,
  "hotel_id" uuid,
  "restaurant_id" uuid,
  "experience_id" uuid,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "xp_reward" integer DEFAULT 10,
  "coin_reward" integer DEFAULT 0,
  "challenge_task" text,
  "photo_required" boolean DEFAULT FALSE,
  "is_mandatory" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- route_stops  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "route_stops" (
  "id" uuid PRIMARY KEY,
  "route_id" uuid NOT NULL,
  "stop_order" integer NOT NULL,
  "destination_id" uuid NOT NULL,
  "place_name" text NOT NULL,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "notes" text
);

-- routes  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "routes" (
  "id" uuid PRIMARY KEY,
  "title" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "description" text,
  "duration_hours" numeric(4,2),
  "distance_km" numeric(6,2),
  "difficulty" text CHECK ("difficulty" IN ('facil', 'moderado', 'dificil')),
  "gpx_track_url" text,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now()
);

-- seo_redirections  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "seo_redirections" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "source_path" text NOT NULL UNIQUE,
  "target_path" text NOT NULL,
  "redirect_type" integer DEFAULT 301 CHECK (redirect_type IN (301, 302)),
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- shopping_centers  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "shopping_centers" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "address" text,
  "phone" text,
  "website" text,
  "image_url" text,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now()
);

-- site_settings  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "site_settings" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "key" text NOT NULL UNIQUE,
  "value" jsonb NOT NULL,
  "description" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- social_comments  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "social_comments" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "post_id" uuid NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamptz DEFAULT now()
);

-- social_likes  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "social_likes" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "post_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  UNIQUE ("user_id", "post_id")
);

-- social_posts  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "social_posts" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "content" text,
  "image_url" text,
  "gallery" jsonb,
  "location" text,
  "destination_id" uuid,
  "likes_count" integer DEFAULT 0,
  "comments_count" integer DEFAULT 0,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- souvenirs  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "souvenirs" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "description" text,
  "typical_price" text,
  "image_url" text,
  "created_at" timestamptz DEFAULT now()
);

-- spas_wellness  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "spas_wellness" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "description" text,
  "address" text,
  "phone" text,
  "website" text,
  "image_url" text,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz DEFAULT now(),
  "is_sponsored" boolean DEFAULT false
);

-- stadiums  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "stadiums" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "stadium_type" text,
  "sport_types" jsonb,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "address" text,
  "phone" text,
  "email" text,
  "website" text,
  "capacity" integer,
  "home_teams" jsonb,
  "facilities" jsonb,
  "services" jsonb,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "rating" numeric(3,2) DEFAULT 0.00,
  "is_featured" boolean DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- store_orders  (supabase/migrations/20260924)
CREATE TABLE IF NOT EXISTS "store_orders" (
  "id" text PRIMARY KEY,
  "user_id" uuid,
  "customer_name" text NOT NULL,
  "customer_email" text NOT NULL,
  "phone" text,
  "address" text NOT NULL,
  "city" text NOT NULL,
  "items" jsonb NOT NULL,
  "subtotal" numeric(12,2) NOT NULL,
  "shipping" numeric(12,2) NOT NULL DEFAULT 0,
  "total" numeric(12,2) NOT NULL,
  "status" text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','shipped','delivered','cancelled')),
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- store_products  (supabase/migrations/20260924)
CREATE TABLE IF NOT EXISTS "store_products" (
  "id" text PRIMARY KEY,
  "slug" text NOT NULL UNIQUE,
  "name" text NOT NULL,
  "category" text NOT NULL CHECK (category IN ('poster','ropa','accesorios','hogar','bolsos')),
  "price" numeric(12,2) NOT NULL CHECK (price >= 0),
  "currency" text NOT NULL DEFAULT 'DOP',
  "stock" integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
  "active" boolean NOT NULL DEFAULT true,
  "featured" boolean NOT NULL DEFAULT false,
  "emoji" text,
  "tone" text,
  "sizes" text[] NOT NULL DEFAULT '{}',
  "colors" text[] NOT NULL DEFAULT '{}',
  "tagline" text,
  "description" text,
  "includes" text[] NOT NULL DEFAULT '{}',
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- support_messages  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "support_messages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "ticket_id" uuid,
  "sender_id" uuid,
  "message" text NOT NULL,
  "is_admin_reply" boolean DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- support_tickets  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "support_tickets" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid,
  "subject" text NOT NULL,
  "description" text NOT NULL,
  "status" text DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  "priority" text DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  "assigned_to" uuid,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- survey_responses  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "survey_responses" (
  "id" uuid PRIMARY KEY,
  "template_id" uuid NOT NULL,
  "user_id" uuid,
  "responses" jsonb NOT NULL,
  "nps_score" integer CHECK ("nps_score" BETWEEN 0 AND 10),
  "created_at" timestamptz DEFAULT now()
);

-- survey_templates  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "survey_templates" (
  "id" uuid PRIMARY KEY,
  "title" text NOT NULL,
  "questions" jsonb NOT NULL,
  "is_active" boolean DEFAULT TRUE
);

-- system_cron_jobs  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "system_cron_jobs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "job_name" text NOT NULL UNIQUE,
  "schedule_cron" text NOT NULL,
  "last_run_at" timestamptz,
  "next_run_at" timestamptz,
  "status" text CHECK (status IN ('idle', 'running', 'success', 'failed')),
  "error_log" text
);

-- system_webhooks  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "system_webhooks" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "url" text NOT NULL,
  "event_type" text NOT NULL,
  "secret_token" text,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- theme_parks  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "theme_parks" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "park_type" text,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "address" text,
  "phone" text,
  "email" text,
  "website" text,
  "price_adult" numeric(10,2),
  "price_child" numeric(10,2),
  "price_range" text,
  "opening_hours" text,
  "attractions" jsonb,
  "services" jsonb,
  "includes" jsonb,
  "age_restrictions" text,
  "duration_recommended" text,
  "latitude" numeric(10,8),
  "longitude" numeric(11,8),
  "rating" numeric(3,2) DEFAULT 0.00,
  "is_featured" boolean DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- toll_routes  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "toll_routes" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "description" text NOT NULL,
  "tolls_data" jsonb NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- tour_guides  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "tour_guides" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "languages" jsonb,
  "bio" text,
  "avatar_url" text,
  "rating" numeric(3,2) DEFAULT 5.00,
  "price_per_day" numeric(10,2),
  "phone" text,
  "email" text,
  "specialties" jsonb,
  "is_active" boolean DEFAULT TRUE,
  "is_eco_guide" boolean DEFAULT FALSE,
  "eco_license" text,
  "created_at" timestamptz DEFAULT now()
);

-- tour_operators  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "tour_operators" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "description" text,
  "logo_url" text,
  "address" text,
  "phone" text,
  "email" text,
  "website" text,
  "is_active" boolean DEFAULT TRUE,
  "is_verified" boolean DEFAULT FALSE,
  "verification_status" text DEFAULT 'pending',
  "verified_at" timestamptz,
  "verification_notes" text,
  "created_at" timestamptz DEFAULT now()
);

-- tour_packages  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "tour_packages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "destination_id" uuid,
  "description" text,
  "short_description" text,
  "image_url" text,
  "gallery" jsonb,
  "duration" text,
  "difficulty" text,
  "price_from" numeric(10,2),
  "price_range" text,
  "max_group_size" integer,
  "min_age" integer,
  "included" jsonb,
  "not_included" jsonb,
  "highlights" jsonb,
  "requirements" jsonb,
  "languages" jsonb,
  "departure_point" text,
  "best_season" text,
  "category" text,
  "rating" numeric(3,2) DEFAULT 0.00,
  "is_featured" boolean DEFAULT FALSE,
  "is_sponsored" boolean DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- travel_agencies  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "travel_agencies" (
  "id" uuid PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "description" text,
  "logo_url" text,
  "address" text,
  "phone" text,
  "email" text,
  "website" text,
  "services" jsonb,
  "is_active" boolean DEFAULT TRUE,
  "is_verified" boolean DEFAULT FALSE,
  "verification_status" text DEFAULT 'pending',
  "verified_at" timestamptz,
  "verification_notes" text,
  "created_at" timestamptz DEFAULT now()
);

-- trivia_questions  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "trivia_questions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "question" text NOT NULL,
  "options" jsonb NOT NULL,
  "correct_index" integer NOT NULL,
  "category" text NOT NULL DEFAULT 'general',
  "difficulty" text NOT NULL DEFAULT 'medium',
  "explanation" text,
  "xp_reward" integer NOT NULL DEFAULT 10,
  "image_url" text,
  "is_active" boolean NOT NULL DEFAULT TRUE,
  "times_answered" integer NOT NULL DEFAULT 0,
  "times_correct" integer NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

-- trivia_sessions  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "trivia_sessions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL,
  "score" integer NOT NULL DEFAULT 0,
  "total_questions" integer NOT NULL DEFAULT 0,
  "correct_answers" integer NOT NULL DEFAULT 0,
  "xp_earned" integer NOT NULL DEFAULT 0,
  "coins_earned" integer NOT NULL DEFAULT 0,
  "max_streak" integer NOT NULL DEFAULT 0,
  "duration_seconds" integer,
  "completed_at" timestamptz NOT NULL DEFAULT now(),
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- ugc_media  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "ugc_media" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid,
  "media_url" text NOT NULL,
  "media_type" text CHECK (media_type IN ('photo', 'video')),
  "associated_entity_type" text NOT NULL,
  "associated_entity_id" uuid NOT NULL,
  "status" text DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- ugc_reports  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "ugc_reports" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "target_type" text NOT NULL,
  "target_id" uuid NOT NULL,
  "reason" text NOT NULL,
  "status" text DEFAULT 'pendiente' CHECK ("status" IN ('pendiente', 'revisado', 'ignorado')),
  "created_at" timestamptz DEFAULT now()
);

-- user_achievements  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_achievements" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "achievement_id" uuid NOT NULL,
  "progress" integer DEFAULT 0,
  "unlocked_at" timestamptz,
  UNIQUE ("user_id", "achievement_id")
);

-- user_checkpoint_completions  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_checkpoint_completions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL,
  "route_id" uuid NOT NULL,
  "checkpoint_id" uuid NOT NULL,
  "completed_at" timestamptz DEFAULT now(),
  "photo_url" text,
  "notes" text,
  "verification_data" jsonb,
  "xp_earned" integer DEFAULT 0,
  "coins_earned" integer DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("user_id", "checkpoint_id")
);

-- user_collectibles  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_collectibles" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL,
  "collectible_id" uuid NOT NULL,
  "acquired_at" timestamptz DEFAULT now(),
  "acquisition_method" text,
  "is_favorite" boolean DEFAULT FALSE,
  "display_order" integer,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("user_id", "collectible_id")
);

-- user_flags  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_flags" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "flag_name" text NOT NULL,
  "value" text,
  "updated_at" timestamptz DEFAULT now(),
  "created_at" timestamptz DEFAULT now(),
  UNIQUE ("user_id", "flag_name")
);

-- user_gamification  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_gamification" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL UNIQUE,
  "total_xp" integer DEFAULT 0,
  "coins" integer DEFAULT 0,
  "current_level" integer DEFAULT 1,
  "streak_days" integer DEFAULT 0,
  "total_missions_completed" integer DEFAULT 0,
  "total_purchases" integer DEFAULT 0,
  "total_referrals" integer DEFAULT 0,
  "last_activity_date" date,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- user_league_stats  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_league_stats" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "season_id" uuid NOT NULL,
  "league_slug" text NOT NULL DEFAULT 'bronze',
  "xp_this_week" integer NOT NULL DEFAULT 0,
  "xp_this_season" integer NOT NULL DEFAULT 0,
  "week_rank" integer,
  "season_rank" integer,
  "last_updated" timestamptz DEFAULT now(),
  UNIQUE ("user_id", "season_id")
);

-- user_missions  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_missions" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "mission_id" uuid NOT NULL,
  "progress" integer NOT NULL DEFAULT 0,
  "is_completed" boolean DEFAULT FALSE,
  "completed_at" timestamptz,
  "updated_at" timestamptz DEFAULT now(),
  UNIQUE ("user_id", "mission_id")
);

-- user_prize_redemptions  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_prize_redemptions" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "prize_id" uuid NOT NULL,
  "coins_spent" integer NOT NULL,
  "status" text DEFAULT 'pending',
  "redemption_code" text,
  "redeemed_at" timestamptz,
  "created_at" timestamptz DEFAULT now()
);

-- user_roles  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_roles" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "role" text NOT NULL CHECK ("role" IN ('admin', 'moderator', 'user')),
  "created_at" timestamptz DEFAULT now(),
  UNIQUE ("user_id", "role")
);

-- user_route_progress  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_route_progress" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL,
  "route_id" uuid NOT NULL,
  "started_at" timestamptz DEFAULT now(),
  "completed_at" timestamptz,
  "current_checkpoint" integer DEFAULT 0,
  "checkpoints_completed" integer DEFAULT 0,
  "total_checkpoints" integer DEFAULT 0,
  "total_xp_earned" integer DEFAULT 0,
  "total_coins_earned" integer DEFAULT 0,
  "is_completed" boolean DEFAULT FALSE,
  "completion_percentage" integer DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("user_id", "route_id")
);

-- user_suspensions  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_suspensions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid,
  "reason" text NOT NULL,
  "suspended_by" uuid,
  "expires_at" timestamptz,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- user_xp_milestones  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "user_xp_milestones" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "milestone_id" uuid NOT NULL,
  "achieved_at" timestamptz DEFAULT now(),
  UNIQUE ("user_id", "milestone_id")
);

-- users  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "users" (
  "id" uuid PRIMARY KEY,
  "email" text NOT NULL UNIQUE,
  "password_hash" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- vacation_registrations  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "vacation_registrations" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "destination_id" uuid NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "notes" text,
  "created_at" timestamptz DEFAULT now()
);

-- vendor_payments  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "vendor_payments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "partner_id" uuid,
  "amount" numeric(10,2) NOT NULL,
  "status" text DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'failed')),
  "payout_method" text,
  "payout_reference" text,
  "paid_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- weather_alerts  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "weather_alerts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "province_id" uuid,
  "alert_type" text CHECK (alert_type IN ('sargazo', 'clima_adverso', 'oleaje_alto', 'huracan', 'otro')),
  "severity" text CHECK (severity IN ('informativa', 'moderada', 'grave', 'extrema')),
  "title" text NOT NULL,
  "description" text NOT NULL,
  "expires_at" timestamptz,
  "is_active" boolean DEFAULT TRUE,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- xp_milestones  (mysql/schema.sql)
CREATE TABLE IF NOT EXISTS "xp_milestones" (
  "id" uuid PRIMARY KEY,
  "xp_threshold" integer NOT NULL UNIQUE,
  "badge_icon" text NOT NULL,
  "badge_name" text NOT NULL,
  "coin_reward" integer NOT NULL DEFAULT 0,
  "description" text
);

-- ===== Índices =====
CREATE INDEX IF NOT EXISTS "idx_ambassadors_code" ON "ambassadors" ("referral_code");
CREATE INDEX IF NOT EXISTS "idx_digital_collectibles_rarity" ON "digital_collectibles" ("rarity");
CREATE INDEX IF NOT EXISTS "idx_event_tickets_code" ON "event_tickets" ("ticket_code");
CREATE INDEX IF NOT EXISTS "idx_partner_profiles_type" ON "partner_profiles" ("business_type");
CREATE INDEX IF NOT EXISTS "idx_passport_stamps_user_id" ON "passport_stamps" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_photo_submissions_challenge_approved" ON "photo_submissions" ("challenge_id", "is_approved");
CREATE INDEX IF NOT EXISTS "idx_reservations_status" ON "reservations" ("partner_id", "status");
CREATE INDEX IF NOT EXISTS "idx_route_checkpoints_route_id" ON "route_checkpoints" ("route_id");
CREATE INDEX IF NOT EXISTS "idx_user_checkpoint_completions_user_route" ON "user_checkpoint_completions" ("user_id", "route_id");
CREATE INDEX IF NOT EXISTS "idx_user_collectibles_user_id" ON "user_collectibles" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_missions_completed" ON "user_missions" ("user_id", "is_completed");
CREATE INDEX IF NOT EXISTS "idx_user_route_progress_user_id" ON "user_route_progress" ("user_id");

-- ===== Claves foráneas =====
DO $$ BEGIN ALTER TABLE "admin_activity_logs" ADD CONSTRAINT "fk_admin_activity_logs_admin_id" FOREIGN KEY ("admin_id") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "airbnb_listings" ADD CONSTRAINT "fk_airbnb_listings_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "ambassador_payouts" ADD CONSTRAINT "fk_ambassador_payouts_ambassador_id" FOREIGN KEY ("ambassador_id") REFERENCES "ambassadors" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "ambassador_referrals" ADD CONSTRAINT "fk_ambassador_referrals_ambassador_id" FOREIGN KEY ("ambassador_id") REFERENCES "ambassadors" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "ambassadors" ADD CONSTRAINT "fk_ambassadors_id" FOREIGN KEY ("id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "article_translations" ADD CONSTRAINT "fk_article_translations_article_id" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "artisanal_workshops" ADD CONSTRAINT "fk_artisanal_workshops_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "bars" ADD CONSTRAINT "fk_bars_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "beaches" ADD CONSTRAINT "fk_beaches_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "beaches" ADD CONSTRAINT "fk_beaches_province_id" FOREIGN KEY ("province_id") REFERENCES "provinces" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "blog_posts" ADD CONSTRAINT "fk_blog_posts_author_id" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "caves" ADD CONSTRAINT "fk_caves_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "clinics" ADD CONSTRAINT "fk_clinics_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "coffee_experiences" ADD CONSTRAINT "fk_coffee_experiences_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "destinations" ADD CONSTRAINT "fk_destinations_province_id" FOREIGN KEY ("province_id") REFERENCES "provinces" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "digital_collectibles" ADD CONSTRAINT "fk_digital_collectibles_event_id" FOREIGN KEY ("event_id") REFERENCES "events" ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "emergency_contacts" ADD CONSTRAINT "fk_emergency_contacts_province_id" FOREIGN KEY ("province_id") REFERENCES "provinces" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "event_tickets" ADD CONSTRAINT "fk_event_tickets_reservation_id" FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "events" ADD CONSTRAINT "fk_events_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "experiences" ADD CONSTRAINT "fk_experiences_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "explorer_follows" ADD CONSTRAINT "fk_explorer_follows_follower_id" FOREIGN KEY ("follower_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "explorer_follows" ADD CONSTRAINT "fk_explorer_follows_following_id" FOREIGN KEY ("following_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "explorer_guilds" ADD CONSTRAINT "fk_explorer_guilds_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "favorites" ADD CONSTRAINT "fk_favorites_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "gamification_transactions" ADD CONSTRAINT "fk_gamification_transactions_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "gamified_routes" ADD CONSTRAINT "fk_gamified_routes_completion_badge_id" FOREIGN KEY ("completion_badge_id") REFERENCES "gamification_prizes" ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "golf_courses" ADD CONSTRAINT "fk_golf_courses_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "guild_members" ADD CONSTRAINT "fk_guild_members_guild_id" FOREIGN KEY ("guild_id") REFERENCES "explorer_guilds" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "guild_members" ADD CONSTRAINT "fk_guild_members_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "hotels" ADD CONSTRAINT "fk_hotels_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "lottery_draws" ADD CONSTRAINT "fk_lottery_draws_lottery_id" FOREIGN KEY ("lottery_id") REFERENCES "lotteries" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "lottery_results" ADD CONSTRAINT "fk_lottery_results_draw_id" FOREIGN KEY ("draw_id") REFERENCES "lottery_draws" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "marketplace_order_items" ADD CONSTRAINT "fk_marketplace_order_items_order_id" FOREIGN KEY ("order_id") REFERENCES "marketplace_orders" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "marketplace_orders" ADD CONSTRAINT "fk_marketplace_orders_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "monuments" ADD CONSTRAINT "fk_monuments_province_id" FOREIGN KEY ("province_id") REFERENCES "provinces" ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "monuments" ADD CONSTRAINT "fk_monuments_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "municipalities" ADD CONSTRAINT "fk_municipalities_province_id" FOREIGN KEY ("province_id") REFERENCES "provinces" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "operator_listings" ADD CONSTRAINT "fk_operator_listings_org_id" FOREIGN KEY ("org_id") REFERENCES "partner_profiles" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "operator_messages" ADD CONSTRAINT "fk_operator_messages_org_id" FOREIGN KEY ("org_id") REFERENCES "partner_profiles" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "operator_promotions" ADD CONSTRAINT "fk_operator_promotions_org_id" FOREIGN KEY ("org_id") REFERENCES "partner_profiles" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "operator_promotions" ADD CONSTRAINT "fk_operator_promotions_listing_id" FOREIGN KEY ("listing_id") REFERENCES "operator_listings" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "operator_reviews" ADD CONSTRAINT "fk_operator_reviews_org_id" FOREIGN KEY ("org_id") REFERENCES "partner_profiles" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "operator_reviews" ADD CONSTRAINT "fk_operator_reviews_listing_id" FOREIGN KEY ("listing_id") REFERENCES "operator_listings" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "parks" ADD CONSTRAINT "fk_parks_province_id" FOREIGN KEY ("province_id") REFERENCES "provinces" ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "parks" ADD CONSTRAINT "fk_parks_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "partner_profiles" ADD CONSTRAINT "fk_partner_profiles_id" FOREIGN KEY ("id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "passport_stamps" ADD CONSTRAINT "fk_passport_stamps_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "passport_stamps" ADD CONSTRAINT "fk_passport_stamps_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "passport_stamps" ADD CONSTRAINT "fk_passport_stamps_beach_id" FOREIGN KEY ("beach_id") REFERENCES "beaches" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "passport_stamps" ADD CONSTRAINT "fk_passport_stamps_hotel_id" FOREIGN KEY ("hotel_id") REFERENCES "hotels" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "passport_stamps" ADD CONSTRAINT "fk_passport_stamps_restaurant_id" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "passport_stamps" ADD CONSTRAINT "fk_passport_stamps_experience_id" FOREIGN KEY ("experience_id") REFERENCES "experiences" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "photo_submissions" ADD CONSTRAINT "fk_photo_submissions_challenge_id" FOREIGN KEY ("challenge_id") REFERENCES "photo_challenges" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "photo_submissions" ADD CONSTRAINT "fk_photo_submissions_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "photo_votes" ADD CONSTRAINT "fk_photo_votes_submission_id" FOREIGN KEY ("submission_id") REFERENCES "photo_submissions" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "photo_votes" ADD CONSTRAINT "fk_photo_votes_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "points_transactions" ADD CONSTRAINT "fk_points_transactions_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "ports_marinas" ADD CONSTRAINT "fk_ports_marinas_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "post_comments" ADD CONSTRAINT "fk_post_comments_post_id" FOREIGN KEY ("post_id") REFERENCES "blog_posts" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "post_comments" ADD CONSTRAINT "fk_post_comments_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "post_likes" ADD CONSTRAINT "fk_post_likes_post_id" FOREIGN KEY ("post_id") REFERENCES "blog_posts" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "post_likes" ADD CONSTRAINT "fk_post_likes_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "profiles" ADD CONSTRAINT "fk_profiles_id" FOREIGN KEY ("id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "province_visits" ADD CONSTRAINT "fk_province_visits_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "referral_codes" ADD CONSTRAINT "fk_referral_codes_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "referral_uses" ADD CONSTRAINT "fk_referral_uses_referral_code_id" FOREIGN KEY ("referral_code_id") REFERENCES "referral_codes" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "referral_uses" ADD CONSTRAINT "fk_referral_uses_referred_user_id" FOREIGN KEY ("referred_user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "reservations" ADD CONSTRAINT "fk_reservations_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "restaurants" ADD CONSTRAINT "fk_restaurants_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "reviews" ADD CONSTRAINT "fk_reviews_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "reward_shipments" ADD CONSTRAINT "fk_reward_shipments_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "reward_shipments" ADD CONSTRAINT "fk_reward_shipments_reward_id" FOREIGN KEY ("reward_id") REFERENCES "reward_inventory" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "rivers" ADD CONSTRAINT "fk_rivers_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "route_checkpoints" ADD CONSTRAINT "fk_route_checkpoints_route_id" FOREIGN KEY ("route_id") REFERENCES "gamified_routes" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "route_checkpoints" ADD CONSTRAINT "fk_route_checkpoints_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "route_checkpoints" ADD CONSTRAINT "fk_route_checkpoints_beach_id" FOREIGN KEY ("beach_id") REFERENCES "beaches" ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "route_checkpoints" ADD CONSTRAINT "fk_route_checkpoints_hotel_id" FOREIGN KEY ("hotel_id") REFERENCES "hotels" ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "route_checkpoints" ADD CONSTRAINT "fk_route_checkpoints_restaurant_id" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "route_checkpoints" ADD CONSTRAINT "fk_route_checkpoints_experience_id" FOREIGN KEY ("experience_id") REFERENCES "experiences" ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "route_stops" ADD CONSTRAINT "fk_route_stops_route_id" FOREIGN KEY ("route_id") REFERENCES "routes" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "route_stops" ADD CONSTRAINT "fk_route_stops_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "shopping_centers" ADD CONSTRAINT "fk_shopping_centers_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "social_comments" ADD CONSTRAINT "fk_social_comments_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "social_comments" ADD CONSTRAINT "fk_social_comments_post_id" FOREIGN KEY ("post_id") REFERENCES "social_posts" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "social_likes" ADD CONSTRAINT "fk_social_likes_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "social_likes" ADD CONSTRAINT "fk_social_likes_post_id" FOREIGN KEY ("post_id") REFERENCES "social_posts" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "social_posts" ADD CONSTRAINT "fk_social_posts_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "social_posts" ADD CONSTRAINT "fk_social_posts_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "spas_wellness" ADD CONSTRAINT "fk_spas_wellness_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "stadiums" ADD CONSTRAINT "fk_stadiums_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "support_messages" ADD CONSTRAINT "fk_support_messages_ticket_id" FOREIGN KEY ("ticket_id") REFERENCES "support_tickets" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "support_messages" ADD CONSTRAINT "fk_support_messages_sender_id" FOREIGN KEY ("sender_id") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "support_tickets" ADD CONSTRAINT "fk_support_tickets_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "support_tickets" ADD CONSTRAINT "fk_support_tickets_assigned_to" FOREIGN KEY ("assigned_to") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "survey_responses" ADD CONSTRAINT "fk_survey_responses_template_id" FOREIGN KEY ("template_id") REFERENCES "survey_templates" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "survey_responses" ADD CONSTRAINT "fk_survey_responses_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "theme_parks" ADD CONSTRAINT "fk_theme_parks_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "tour_packages" ADD CONSTRAINT "fk_tour_packages_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "trivia_sessions" ADD CONSTRAINT "fk_trivia_sessions_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "ugc_media" ADD CONSTRAINT "fk_ugc_media_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "ugc_reports" ADD CONSTRAINT "fk_ugc_reports_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_achievements" ADD CONSTRAINT "fk_user_achievements_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_achievements" ADD CONSTRAINT "fk_user_achievements_achievement_id" FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_checkpoint_completions" ADD CONSTRAINT "fk_user_checkpoint_completions_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_checkpoint_completions" ADD CONSTRAINT "fk_user_checkpoint_completions_route_id" FOREIGN KEY ("route_id") REFERENCES "gamified_routes" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_checkpoint_completions" ADD CONSTRAINT "fk_user_checkpoint_completions_checkpoint_id" FOREIGN KEY ("checkpoint_id") REFERENCES "route_checkpoints" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_collectibles" ADD CONSTRAINT "fk_user_collectibles_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_collectibles" ADD CONSTRAINT "fk_user_collectibles_collectible_id" FOREIGN KEY ("collectible_id") REFERENCES "digital_collectibles" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_flags" ADD CONSTRAINT "fk_user_flags_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_gamification" ADD CONSTRAINT "fk_user_gamification_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_league_stats" ADD CONSTRAINT "fk_user_league_stats_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_league_stats" ADD CONSTRAINT "fk_user_league_stats_season_id" FOREIGN KEY ("season_id") REFERENCES "gamification_seasons" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_missions" ADD CONSTRAINT "fk_user_missions_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_missions" ADD CONSTRAINT "fk_user_missions_mission_id" FOREIGN KEY ("mission_id") REFERENCES "gamification_missions" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_prize_redemptions" ADD CONSTRAINT "fk_user_prize_redemptions_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_prize_redemptions" ADD CONSTRAINT "fk_user_prize_redemptions_prize_id" FOREIGN KEY ("prize_id") REFERENCES "gamification_prizes" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_route_progress" ADD CONSTRAINT "fk_user_route_progress_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_route_progress" ADD CONSTRAINT "fk_user_route_progress_route_id" FOREIGN KEY ("route_id") REFERENCES "gamified_routes" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_suspensions" ADD CONSTRAINT "fk_user_suspensions_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_suspensions" ADD CONSTRAINT "fk_user_suspensions_suspended_by" FOREIGN KEY ("suspended_by") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_xp_milestones" ADD CONSTRAINT "fk_user_xp_milestones_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "user_xp_milestones" ADD CONSTRAINT "fk_user_xp_milestones_milestone_id" FOREIGN KEY ("milestone_id") REFERENCES "xp_milestones" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "vacation_registrations" ADD CONSTRAINT "fk_vacation_registrations_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "vacation_registrations" ADD CONSTRAINT "fk_vacation_registrations_destination_id" FOREIGN KEY ("destination_id") REFERENCES "destinations" ("id") ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "vendor_payments" ADD CONSTRAINT "fk_vendor_payments_partner_id" FOREIGN KEY ("partner_id") REFERENCES "users" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "weather_alerts" ADD CONSTRAINT "fk_weather_alerts_province_id" FOREIGN KEY ("province_id") REFERENCES "provinces" ("id") ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ===== updated_at automático =====
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT table_name FROM information_schema.columns
           WHERE table_schema = 'public' AND column_name = 'updated_at'
             AND table_name IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE')
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_set_updated_at ON %I', r.table_name);
    EXECUTE format('CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()', r.table_name);
  END LOOP;
END $$;
