-- Búsqueda de contenido público (docs §5.3/§5.4): texto sin acentos ni mayúsculas con índices trigram,
-- y la colección `mountains` que hoy vive en src/data/mountains.ts (aún no conectada).

-- unaccent() no es IMMUTABLE; este envoltorio permite usarlo en índices.
CREATE OR REPLACE FUNCTION f_unaccent(input text) RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT AS $$ SELECT public.unaccent('public.unaccent', input) $$;

CREATE TABLE IF NOT EXISTS mountains (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE,
  name text NOT NULL,
  altitude_m integer,
  mountain_range text CHECK (mountain_range IN ('cordillera-central', 'sierra-bahoruco', 'cordillera-septentrional', 'sierra-neiba', 'sierra-yamasa', 'peninsula-samana', 'otra')),
  range_name text,
  province_id uuid REFERENCES provinces(id) ON DELETE SET NULL,
  short_description text,
  description text,
  image_url text,
  gallery jsonb NOT NULL DEFAULT '[]',
  activities jsonb NOT NULL DEFAULT '[]',
  difficulty text CHECK (difficulty IN ('facil', 'moderado', 'dificil', 'experto')),
  duration text,
  best_season text,
  flora jsonb NOT NULL DEFAULT '[]',
  fauna jsonb NOT NULL DEFAULT '[]',
  highlights jsonb NOT NULL DEFAULT '[]',
  how_to_get_there text,
  safety_tips jsonb NOT NULL DEFAULT '[]',
  guides_required boolean NOT NULL DEFAULT false,
  price_range text,
  rating numeric(3,2),
  review_count integer NOT NULL DEFAULT 0,
  is_popular boolean NOT NULL DEFAULT false,
  is_featured boolean NOT NULL DEFAULT false,
  latitude numeric(10,8),
  longitude numeric(11,8),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  -- gobierno CMS (docs §4.1)
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'in_review', 'published', 'archived')),
  published_at timestamptz,
  unpublished_at timestamptz,
  slug_history text[] NOT NULL DEFAULT '{}',
  seo_title text,
  seo_description text,
  og_image_url text,
  canonical_url text,
  noindex boolean NOT NULL DEFAULT false,
  locale_default text NOT NULL DEFAULT 'es',
  created_by uuid REFERENCES users(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES users(id) ON DELETE SET NULL,
  reviewed_by uuid REFERENCES users(id) ON DELETE SET NULL,
  version integer NOT NULL DEFAULT 1,
  deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_mountains_status ON mountains (status) WHERE deleted_at IS NULL;
DROP TRIGGER IF EXISTS trg_set_updated_at ON mountains;
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON mountains FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Índices trigram sobre los campos de búsqueda de cada colección (omite tablas/columnas que no existan).
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('provinces', 'name'),
    ('municipalities', 'name'),
    ('municipalities', 'short_description'),
    ('destinations', 'name'),
    ('destinations', 'short_description'),
    ('beaches', 'name'),
    ('beaches', 'short_description'),
    ('mountains', 'name'),
    ('mountains', 'short_description'),
    ('rivers', 'name'),
    ('rivers', 'short_description'),
    ('parks', 'name'),
    ('parks', 'short_description'),
    ('protected_areas', 'name'),
    ('protected_areas', 'location'),
    ('caves', 'name'),
    ('caves', 'short_description'),
    ('hot_springs', 'name'),
    ('hot_springs', 'location'),
    ('monuments', 'name'),
    ('monuments', 'short_description'),
    ('bird_species', 'name'),
    ('bird_species', 'scientific_name'),
    ('offset_projects', 'title'),
    ('offset_projects', 'location'),
    ('toll_routes', 'name'),
    ('hotels', 'name'),
    ('hotels', 'short_description'),
    ('airbnb_listings', 'name'),
    ('airbnb_listings', 'short_description'),
    ('restaurants', 'name'),
    ('restaurants', 'short_description'),
    ('bars', 'name'),
    ('bars', 'short_description'),
    ('spas_wellness', 'name'),
    ('spas_wellness', 'short_description'),
    ('experiences', 'title'),
    ('experiences', 'name'),
    ('experiences', 'short_description'),
    ('tour_packages', 'name'),
    ('tour_packages', 'short_description'),
    ('events', 'title'),
    ('events', 'location'),
    ('clinics', 'name'),
    ('clinics', 'address'),
    ('ports_marinas', 'name'),
    ('ports_marinas', 'short_description'),
    ('stadiums', 'name'),
    ('stadiums', 'short_description'),
    ('theme_parks', 'name'),
    ('theme_parks', 'short_description'),
    ('golf_courses', 'name'),
    ('golf_courses', 'short_description'),
    ('shopping_centers', 'name'),
    ('shopping_centers', 'address'),
    ('souvenirs', 'name'),
    ('artisanal_workshops', 'name'),
    ('artisanal_workshops', 'short_description'),
    ('coffee_experiences', 'name'),
    ('coffee_experiences', 'short_description'),
    ('tour_guides', 'name'),
    ('travel_agencies', 'name'),
    ('tour_operators', 'name'),
    ('establecimientos', 'nombre'),
    ('establecimientos', 'actividad'),
    ('establecimientos', 'subsector'),
    ('establecimientos', 'sector_zona'),
    ('historical_figures', 'name'),
    ('historical_figures', 'title'),
    ('historical_figures', 'short_description'),
    ('historical_events', 'name'),
    ('historical_events', 'short_description'),
    ('articles', 'title'),
    ('articles', 'excerpt'),
    ('routes', 'title'),
    ('audio_guides', 'title'),
    ('job_vacancies', 'title'),
    ('job_vacancies', 'company_name'),
    ('job_vacancies', 'short_description'),
    ('job_vacancies', 'location'),
    ('emergency_contacts', 'institution'),
    ('emergency_contacts', 'address'),
    ('offers', 'title')
  ) AS t(tbl, col)
  LOOP
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = r.tbl AND column_name = r.col AND data_type = 'text') THEN
      EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I USING gin (lower(f_unaccent(%I)) gin_trgm_ops)', 'trgm_' || left(r.tbl, 24) || '_' || left(r.col, 20), r.tbl, r.col);
    END IF;
  END LOOP;
END $$;
