import type { Rendered, TemplateData, TemplateKey } from "./templates-types.js";

/** Idiomas adicionales de los correos al viajero (fr, de, pt, it). Los correos al personal de operadores, vendedores y embajadores quedan en es/en. */
export type ExtraLocale = "fr" | "de" | "pt" | "it";
export const EXTRA_LOCALES: readonly ExtraLocale[] = ["fr", "de", "pt", "it"];
export interface Helpers {
  layout: (title: string, body: string, cta?: { label: string; url: string }, footer?: string, lang?: string) => string;
  p: (s: string) => string;
  table: (rows: [string, string][]) => string;
  esc: (s: string) => string;
}
interface Copy { subject: string; title: string; body: string[]; rows?: [string, string][]; cta?: { label: string; url: string }; footer?: string }
type Data = TemplateData;
type Book = Data["booking.reminder"];

/** Etiquetas comunes por idioma. */
const L: Record<ExtraLocale, { service: string; dates: string; guests: string; total: string; paid: string; balance: string; reference: string; items: string; order: string; hi: string; ignore: string; unsub: string; footer: string }> = {
  fr: { service: "Service", dates: "Dates", guests: "Personnes", total: "Total", paid: "Payé", balance: "Solde à payer", reference: "Référence", items: "Articles", order: "Commande", hi: "Bonjour", ignore: "Si ce n'était pas vous, ignorez ce message.", unsub: "Se désabonner", footer: "Descubre RD · République dominicaine" },
  de: { service: "Leistung", dates: "Datum", guests: "Personen", total: "Gesamt", paid: "Bezahlt", balance: "Offener Betrag", reference: "Referenz", items: "Artikel", order: "Bestellung", hi: "Hallo", ignore: "Falls Sie das nicht waren, ignorieren Sie diese Nachricht.", unsub: "Abmelden", footer: "Descubre RD · Dominikanische Republik" },
  pt: { service: "Serviço", dates: "Datas", guests: "Pessoas", total: "Total", paid: "Pago", balance: "Saldo pendente", reference: "Referência", items: "Artigos", order: "Pedido", hi: "Olá", ignore: "Se não foi você, ignore esta mensagem.", unsub: "Cancelar inscrição", footer: "Descubre RD · República Dominicana" },
  it: { service: "Servizio", dates: "Date", guests: "Persone", total: "Totale", paid: "Pagato", balance: "Saldo da pagare", reference: "Riferimento", items: "Articoli", order: "Ordine", hi: "Ciao", ignore: "Se non sei stato tu, ignora questo messaggio.", unsub: "Annulla l'iscrizione", footer: "Descubre RD · Repubblica Dominicana" },
};
const bookRows = (l: ExtraLocale, d: Book): [string, string][] => [[L[l].service, d.service], [L[l].dates, d.dates], [L[l].guests, d.guests], [L[l].total, d.total], [L[l].reference, d.reference]];

type Copies = { [K in TemplateKey]?: (d: Data[K]) => Copy };
const C: Record<ExtraLocale, Copies> = {
  fr: {
    "auth.verify_email": (d) => ({ subject: "Confirmez votre e-mail sur Descubre RD", title: "Confirmez votre e-mail", body: [`Bonjour ${d.name},`, `Confirmez votre e-mail pour activer les réservations, les achats et toutes les fonctions de votre compte. Le lien expire dans ${d.hours} heures.`, "Si vous n'avez pas créé ce compte, ignorez ce message."], cta: { label: "Confirmer mon e-mail", url: d.url } }),
    "auth.welcome": (d) => ({ subject: "Bienvenue sur Descubre RD !", title: "Bienvenue sur Descubre RD !", body: [`Bonjour ${d.name}, votre e-mail est confirmé.`, "Enregistrez vos favoris, planifiez votre voyage et gagnez des points en explorant la République dominicaine."], cta: { label: "Commencer à explorer", url: d.url } }),
    "auth.reset_password": (d) => ({ subject: "Réinitialisez votre mot de passe", title: "Réinitialisez votre mot de passe", body: [`Bonjour ${d.name},`, `Nous avons reçu une demande de réinitialisation de votre mot de passe. Le lien expire dans ${d.minutes} minutes.`, "Si ce n'était pas vous, ignorez ce message : votre mot de passe ne changera pas."], cta: { label: "Créer un nouveau mot de passe", url: d.url } }),
    "auth.password_changed": (d) => ({ subject: "Votre mot de passe a été modifié", title: "Votre mot de passe a été modifié", body: [`Bonjour ${d.name},`, "Votre mot de passe Descubre RD vient d'être modifié et vos autres sessions ont été fermées.", "Si ce n'était pas vous, réinitialisez-le immédiatement et contactez le support."] }),
    "auth.two_factor_reset": (d) => ({ subject: "Votre vérification en deux étapes a été réinitialisée", title: "Vérification en deux étapes réinitialisée", body: [`Bonjour ${d.name},`, "Un administrateur a désactivé votre vérification en deux étapes et fermé vos sessions. Réactivez-la à votre prochaine connexion.", "Si vous ne vous y attendiez pas, contactez le support."] }),
    "booking.confirmation": (d) => ({ subject: `Réservation confirmée ${d.reference} — ${d.service}`, title: "Réservation confirmée !", body: [`Bonjour ${d.name}, votre réservation chez ${d.operator} est confirmée.`], rows: [...bookRows("fr", d).slice(0, 4) as [string, string][], [L.fr.paid, d.paid], [L.fr.balance, d.balance], [L.fr.reference, d.reference]], cta: { label: "Voir ma réservation", url: d.url } }),
    "booking.request_received": (d) => ({ subject: `Demande reçue ${d.reference} — ${d.service}`, title: "Demande reçue", body: [`Bonjour ${d.name}, ${d.operator} confirmera votre réservation et vous contactera bientôt.`], rows: bookRows("fr", d), cta: { label: "Voir ma demande", url: d.url } }),
    "booking.cancelled": (d) => ({ subject: `Réservation annulée ${d.reference}`, title: "Réservation annulée", body: [`Bonjour ${d.name}, votre réservation ${d.reference} (${d.service}) chez ${d.operator} a été annulée.`, `Remboursement : ${d.refund}.`] }),
    "booking.balance_due": (d) => ({ subject: `Solde restant de votre réservation ${d.reference}`, title: "Solde restant", body: [`Bonjour ${d.name}, votre sortie ${d.service} avec ${d.operator} a lieu le ${d.date} et il reste ${d.balance} à payer.`], rows: [[L.fr.reference, d.reference]], cta: { label: "Voir ma réservation", url: d.url } }),
    "booking.claim": (d) => ({ subject: `Liez votre réservation avec ${d.organizer}`, title: "Liez votre réservation", body: [`Bonjour ${d.name},`, `Confirmez que la réservation du ${d.dates} avec ${d.organizer} est bien la vôtre : elle sera liée à votre compte Descubre RD.`, `Le lien est à usage unique et expire dans ${d.hours} heures. Si ce n'était pas vous, ignorez ce message.`], cta: { label: "Lier ma réservation", url: d.url } }),
    "booking.reminder": (d) => ({ subject: `Rappel : ${d.service} — ${d.dates}`, title: "Rappel de votre réservation", body: [`Bonjour ${d.name}, nous vous rappelons votre réservation chez ${d.operator}.`], rows: bookRows("fr", d), cta: { label: "Voir ma réservation", url: d.url } }),
    "booking.review_request": (d) => ({ subject: `Comment était ${d.service} ?`, title: "Comment s'est passé votre voyage ?", body: [`Bonjour ${d.name}, merci d'avoir voyagé avec ${d.operator}. Votre avis sur ${d.service} aide les autres voyageurs.`], cta: { label: "Laisser mon avis", url: d.url } }),
    "newsletter.confirm": (d) => ({ subject: "Confirmez votre abonnement à Descubre RD", title: "Confirmez votre abonnement", body: ["Encore une étape pour recevoir les nouveautés de Descubre RD.", "Si ce n'était pas vous, ignorez cet e-mail."], cta: { label: "Confirmer l'abonnement", url: d.url } }),
    "support.received": (d) => ({ subject: `Nous avons reçu votre message (${d.reference})`, title: "Nous avons reçu votre message", body: [`Bonjour ${d.name}, nous avons reçu votre message « ${d.subject} ».`, `Référence : ${d.reference}. Nous vous répondrons dès que possible.`] }),
    "establishment.received": (d) => ({ subject: `Demande reçue pour ${d.establishment}`, title: "Demande reçue", body: [`Bonjour ${d.name}, nous avons reçu la demande d'inscription de ${d.establishment}. Nous l'examinerons et vous répondrons.`], cta: { label: "Voir le statut", url: d.url } }),
    "store.order_confirmation": (d) => ({ subject: `Commande ${d.reference} confirmée`, title: "Merci pour votre achat !", body: [`Bonjour ${d.name}, nous avons reçu votre commande ${d.reference}.`], rows: [[L.fr.items, d.items], [L.fr.total, d.total], [L.fr.order, d.reference]], cta: { label: "Voir ma commande", url: d.url } }),
    "store.order_update": (d) => ({ subject: `${d.title} · ${d.reference}`, title: d.title, body: [`Bonjour ${d.name}, ${d.message}`], rows: [[L.fr.order, d.reference]], cta: { label: "Voir ma commande", url: d.url } }),
  },
  de: {
    "auth.verify_email": (d) => ({ subject: "Bestätigen Sie Ihre E-Mail bei Descubre RD", title: "E-Mail bestätigen", body: [`Hallo ${d.name},`, `Bestätigen Sie Ihre E-Mail, um Buchungen, Einkäufe und alle Kontofunktionen freizuschalten. Der Link ist ${d.hours} Stunden gültig.`, "Falls Sie dieses Konto nicht erstellt haben, ignorieren Sie diese Nachricht."], cta: { label: "Meine E-Mail bestätigen", url: d.url } }),
    "auth.welcome": (d) => ({ subject: "Willkommen bei Descubre RD!", title: "Willkommen bei Descubre RD!", body: [`Hallo ${d.name}, Ihre E-Mail ist bestätigt.`, "Speichern Sie Favoriten, planen Sie Ihre Reise und sammeln Sie Punkte beim Entdecken der Dominikanischen Republik."], cta: { label: "Jetzt entdecken", url: d.url } }),
    "auth.reset_password": (d) => ({ subject: "Passwort zurücksetzen", title: "Passwort zurücksetzen", body: [`Hallo ${d.name},`, `Wir haben eine Anfrage zum Zurücksetzen Ihres Passworts erhalten. Der Link ist ${d.minutes} Minuten gültig.`, "Falls Sie das nicht waren, ignorieren Sie diese Nachricht: Ihr Passwort bleibt unverändert."], cta: { label: "Neues Passwort erstellen", url: d.url } }),
    "auth.password_changed": (d) => ({ subject: "Ihr Passwort wurde geändert", title: "Ihr Passwort wurde geändert", body: [`Hallo ${d.name},`, "Ihr Descubre-RD-Passwort wurde soeben geändert und Ihre anderen Sitzungen wurden abgemeldet.", "Falls Sie das nicht waren, setzen Sie es sofort zurück und kontaktieren Sie den Support."] }),
    "auth.two_factor_reset": (d) => ({ subject: "Ihre Zwei-Faktor-Authentifizierung wurde zurückgesetzt", title: "Zwei-Faktor-Authentifizierung zurückgesetzt", body: [`Hallo ${d.name},`, "Ein Administrator hat Ihre Zwei-Faktor-Authentifizierung deaktiviert und Ihre Sitzungen beendet. Aktivieren Sie sie bei der nächsten Anmeldung erneut.", "Falls Sie das nicht erwartet haben, kontaktieren Sie den Support."] }),
    "booking.confirmation": (d) => ({ subject: `Buchung bestätigt ${d.reference} — ${d.service}`, title: "Buchung bestätigt!", body: [`Hallo ${d.name}, Ihre Buchung bei ${d.operator} ist bestätigt.`], rows: [...bookRows("de", d).slice(0, 4) as [string, string][], [L.de.paid, d.paid], [L.de.balance, d.balance], [L.de.reference, d.reference]], cta: { label: "Meine Buchung ansehen", url: d.url } }),
    "booking.request_received": (d) => ({ subject: `Anfrage erhalten ${d.reference} — ${d.service}`, title: "Anfrage erhalten", body: [`Hallo ${d.name}, ${d.operator} bestätigt Ihre Buchung und meldet sich in Kürze.`], rows: bookRows("de", d), cta: { label: "Meine Anfrage ansehen", url: d.url } }),
    "booking.cancelled": (d) => ({ subject: `Buchung storniert ${d.reference}`, title: "Buchung storniert", body: [`Hallo ${d.name}, Ihre Buchung ${d.reference} (${d.service}) bei ${d.operator} wurde storniert.`, `Erstattung: ${d.refund}.`] }),
    "booking.balance_due": (d) => ({ subject: `Offener Betrag Ihrer Buchung ${d.reference}`, title: "Offener Betrag", body: [`Hallo ${d.name}, Ihre Buchung „${d.service}“ mit ${d.operator} findet am ${d.date} statt und es sind noch ${d.balance} offen.`], rows: [[L.de.reference, d.reference]], cta: { label: "Meine Buchung ansehen", url: d.url } }),
    "booking.claim": (d) => ({ subject: `Buchung mit ${d.organizer} verknüpfen`, title: "Buchung verknüpfen", body: [`Hallo ${d.name},`, `Bestätigen Sie, dass die Buchung vom ${d.dates} bei ${d.organizer} Ihre ist: Sie wird mit Ihrem Descubre-RD-Konto verknüpft.`, `Der Link ist einmalig verwendbar und läuft in ${d.hours} Stunden ab. Falls Sie das nicht waren, ignorieren Sie diese Nachricht.`], cta: { label: "Meine Buchung verknüpfen", url: d.url } }),
    "booking.reminder": (d) => ({ subject: `Erinnerung: ${d.service} — ${d.dates}`, title: "Erinnerung an Ihre Buchung", body: [`Hallo ${d.name}, wir erinnern Sie an Ihre Buchung bei ${d.operator}.`], rows: bookRows("de", d), cta: { label: "Meine Buchung ansehen", url: d.url } }),
    "booking.review_request": (d) => ({ subject: `Wie war ${d.service}?`, title: "Wie war Ihre Reise?", body: [`Hallo ${d.name}, danke, dass Sie mit ${d.operator} gereist sind. Ihre Meinung zu ${d.service} hilft anderen Reisenden.`], cta: { label: "Bewertung abgeben", url: d.url } }),
    "newsletter.confirm": (d) => ({ subject: "Bestätigen Sie Ihr Abonnement bei Descubre RD", title: "Abonnement bestätigen", body: ["Noch ein Schritt, um Neuigkeiten von Descubre RD zu erhalten.", "Falls Sie das nicht waren, ignorieren Sie diese E-Mail."], cta: { label: "Abonnement bestätigen", url: d.url } }),
    "support.received": (d) => ({ subject: `Wir haben Ihre Nachricht erhalten (${d.reference})`, title: "Wir haben Ihre Nachricht erhalten", body: [`Hallo ${d.name}, wir haben Ihre Nachricht „${d.subject}“ erhalten.`, `Referenz: ${d.reference}. Wir antworten so bald wie möglich.`] }),
    "establishment.received": (d) => ({ subject: `Anfrage für ${d.establishment} erhalten`, title: "Anfrage erhalten", body: [`Hallo ${d.name}, wir haben die Anmeldung von ${d.establishment} erhalten. Wir prüfen sie und melden uns.`], cta: { label: "Status ansehen", url: d.url } }),
    "store.order_confirmation": (d) => ({ subject: `Bestellung ${d.reference} bestätigt`, title: "Vielen Dank für Ihren Einkauf!", body: [`Hallo ${d.name}, wir haben Ihre Bestellung ${d.reference} erhalten.`], rows: [[L.de.items, d.items], [L.de.total, d.total], [L.de.order, d.reference]], cta: { label: "Meine Bestellung ansehen", url: d.url } }),
    "store.order_update": (d) => ({ subject: `${d.title} · ${d.reference}`, title: d.title, body: [`Hallo ${d.name}, ${d.message}`], rows: [[L.de.order, d.reference]], cta: { label: "Meine Bestellung ansehen", url: d.url } }),
  },
  pt: {
    "auth.verify_email": (d) => ({ subject: "Confirme seu e-mail no Descubre RD", title: "Confirme seu e-mail", body: [`Olá ${d.name},`, `Confirme seu e-mail para ativar reservas, compras e todas as funções da sua conta. O link expira em ${d.hours} horas.`, "Se você não criou esta conta, ignore esta mensagem."], cta: { label: "Confirmar meu e-mail", url: d.url } }),
    "auth.welcome": (d) => ({ subject: "Bem-vindo ao Descubre RD!", title: "Bem-vindo ao Descubre RD!", body: [`Olá ${d.name}, seu e-mail foi confirmado.`, "Guarde seus favoritos, planeje sua viagem e ganhe pontos explorando a República Dominicana."], cta: { label: "Começar a explorar", url: d.url } }),
    "auth.reset_password": (d) => ({ subject: "Redefina sua senha", title: "Redefina sua senha", body: [`Olá ${d.name},`, `Recebemos um pedido para redefinir sua senha. O link expira em ${d.minutes} minutos.`, "Se não foi você, ignore esta mensagem: sua senha não será alterada."], cta: { label: "Criar nova senha", url: d.url } }),
    "auth.password_changed": (d) => ({ subject: "Sua senha foi alterada", title: "Sua senha foi alterada", body: [`Olá ${d.name},`, "Sua senha do Descubre RD acabou de ser alterada e suas outras sessões foram encerradas.", "Se não foi você, redefina-a imediatamente e fale com o suporte."] }),
    "auth.two_factor_reset": (d) => ({ subject: "Sua verificação em duas etapas foi redefinida", title: "Verificação em duas etapas redefinida", body: [`Olá ${d.name},`, "Um administrador desativou sua verificação em duas etapas e encerrou suas sessões. Ative-a novamente ao entrar.", "Se você não esperava isso, fale com o suporte."] }),
    "booking.confirmation": (d) => ({ subject: `Reserva confirmada ${d.reference} — ${d.service}`, title: "Reserva confirmada!", body: [`Olá ${d.name}, sua reserva com ${d.operator} está confirmada.`], rows: [...bookRows("pt", d).slice(0, 4) as [string, string][], [L.pt.paid, d.paid], [L.pt.balance, d.balance], [L.pt.reference, d.reference]], cta: { label: "Ver minha reserva", url: d.url } }),
    "booking.request_received": (d) => ({ subject: `Solicitação recebida ${d.reference} — ${d.service}`, title: "Solicitação recebida", body: [`Olá ${d.name}, ${d.operator} confirmará sua reserva e entrará em contato em breve.`], rows: bookRows("pt", d), cta: { label: "Ver minha solicitação", url: d.url } }),
    "booking.cancelled": (d) => ({ subject: `Reserva cancelada ${d.reference}`, title: "Reserva cancelada", body: [`Olá ${d.name}, sua reserva ${d.reference} (${d.service}) com ${d.operator} foi cancelada.`, `Reembolso: ${d.refund}.`] }),
    "booking.balance_due": (d) => ({ subject: `Saldo pendente da sua reserva ${d.reference}`, title: "Saldo pendente", body: [`Olá ${d.name}, seu passeio ${d.service} com ${d.operator} é em ${d.date} e há um saldo pendente de ${d.balance}.`], rows: [[L.pt.reference, d.reference]], cta: { label: "Ver minha reserva", url: d.url } }),
    "booking.claim": (d) => ({ subject: `Vincule sua reserva com ${d.organizer}`, title: "Vincule sua reserva", body: [`Olá ${d.name},`, `Confirme que a reserva de ${d.dates} com ${d.organizer} é sua: ela será vinculada à sua conta do Descubre RD.`, `O link é de uso único e expira em ${d.hours} horas. Se não foi você, ignore esta mensagem.`], cta: { label: "Vincular minha reserva", url: d.url } }),
    "booking.reminder": (d) => ({ subject: `Lembrete: ${d.service} — ${d.dates}`, title: "Lembrete da sua reserva", body: [`Olá ${d.name}, lembramos sua reserva com ${d.operator}.`], rows: bookRows("pt", d), cta: { label: "Ver minha reserva", url: d.url } }),
    "booking.review_request": (d) => ({ subject: `Como foi ${d.service}?`, title: "Como foi sua viagem?", body: [`Olá ${d.name}, obrigado por viajar com ${d.operator}. Sua opinião sobre ${d.service} ajuda outros viajantes.`], cta: { label: "Deixar minha avaliação", url: d.url } }),
    "newsletter.confirm": (d) => ({ subject: "Confirme sua inscrição no Descubre RD", title: "Confirme sua inscrição", body: ["Falta só um passo para receber as novidades do Descubre RD.", "Se não foi você, ignore este e-mail."], cta: { label: "Confirmar inscrição", url: d.url } }),
    "support.received": (d) => ({ subject: `Recebemos sua mensagem (${d.reference})`, title: "Recebemos sua mensagem", body: [`Olá ${d.name}, recebemos sua mensagem “${d.subject}”.`, `Referência: ${d.reference}. Responderemos o mais breve possível.`] }),
    "establishment.received": (d) => ({ subject: `Recebemos a solicitação de ${d.establishment}`, title: "Solicitação recebida", body: [`Olá ${d.name}, recebemos a solicitação de cadastro de ${d.establishment}. Vamos analisá-la e avisaremos você.`], cta: { label: "Ver o status", url: d.url } }),
    "store.order_confirmation": (d) => ({ subject: `Pedido ${d.reference} confirmado`, title: "Obrigado pela sua compra!", body: [`Olá ${d.name}, recebemos seu pedido ${d.reference}.`], rows: [[L.pt.items, d.items], [L.pt.total, d.total], [L.pt.order, d.reference]], cta: { label: "Ver meu pedido", url: d.url } }),
    "store.order_update": (d) => ({ subject: `${d.title} · ${d.reference}`, title: d.title, body: [`Olá ${d.name}, ${d.message}`], rows: [[L.pt.order, d.reference]], cta: { label: "Ver meu pedido", url: d.url } }),
  },
  it: {
    "auth.verify_email": (d) => ({ subject: "Conferma la tua e-mail su Descubre RD", title: "Conferma la tua e-mail", body: [`Ciao ${d.name},`, `Conferma la tua e-mail per attivare prenotazioni, acquisti e tutte le funzioni dell'account. Il link scade tra ${d.hours} ore.`, "Se non hai creato tu l'account, ignora questo messaggio."], cta: { label: "Conferma la mia e-mail", url: d.url } }),
    "auth.welcome": (d) => ({ subject: "Benvenuto su Descubre RD!", title: "Benvenuto su Descubre RD!", body: [`Ciao ${d.name}, la tua e-mail è confermata.`, "Salva i preferiti, pianifica il viaggio e guadagna punti esplorando la Repubblica Dominicana."], cta: { label: "Inizia a esplorare", url: d.url } }),
    "auth.reset_password": (d) => ({ subject: "Reimposta la tua password", title: "Reimposta la tua password", body: [`Ciao ${d.name},`, `Abbiamo ricevuto una richiesta di reimpostazione della password. Il link scade tra ${d.minutes} minuti.`, "Se non sei stato tu, ignora questo messaggio: la password non cambierà."], cta: { label: "Crea una nuova password", url: d.url } }),
    "auth.password_changed": (d) => ({ subject: "La tua password è stata modificata", title: "La tua password è stata modificata", body: [`Ciao ${d.name},`, "La tua password di Descubre RD è stata appena modificata e le altre sessioni sono state chiuse.", "Se non sei stato tu, reimpostala subito e contatta l'assistenza."] }),
    "auth.two_factor_reset": (d) => ({ subject: "La verifica in due passaggi è stata reimpostata", title: "Verifica in due passaggi reimpostata", body: [`Ciao ${d.name},`, "Un amministratore ha disattivato la verifica in due passaggi e chiuso le tue sessioni. Riattivala al prossimo accesso.", "Se non te lo aspettavi, contatta l'assistenza."] }),
    "booking.confirmation": (d) => ({ subject: `Prenotazione confermata ${d.reference} — ${d.service}`, title: "Prenotazione confermata!", body: [`Ciao ${d.name}, la tua prenotazione con ${d.operator} è confermata.`], rows: [...bookRows("it", d).slice(0, 4) as [string, string][], [L.it.paid, d.paid], [L.it.balance, d.balance], [L.it.reference, d.reference]], cta: { label: "Vedi la mia prenotazione", url: d.url } }),
    "booking.request_received": (d) => ({ subject: `Richiesta ricevuta ${d.reference} — ${d.service}`, title: "Richiesta ricevuta", body: [`Ciao ${d.name}, ${d.operator} confermerà la prenotazione e ti contatterà presto.`], rows: bookRows("it", d), cta: { label: "Vedi la mia richiesta", url: d.url } }),
    "booking.cancelled": (d) => ({ subject: `Prenotazione annullata ${d.reference}`, title: "Prenotazione annullata", body: [`Ciao ${d.name}, la prenotazione ${d.reference} (${d.service}) con ${d.operator} è stata annullata.`, `Rimborso: ${d.refund}.`] }),
    "booking.balance_due": (d) => ({ subject: `Saldo da pagare della prenotazione ${d.reference}`, title: "Saldo da pagare", body: [`Ciao ${d.name}, la tua uscita ${d.service} con ${d.operator} è il ${d.date} e ci sono ancora ${d.balance} da pagare.`], rows: [[L.it.reference, d.reference]], cta: { label: "Vedi la mia prenotazione", url: d.url } }),
    "booking.claim": (d) => ({ subject: `Collega la tua prenotazione a ${d.organizer}`, title: "Collega la tua prenotazione", body: [`Ciao ${d.name},`, `Conferma che la prenotazione del ${d.dates} con ${d.organizer} è tua: sarà collegata al tuo account Descubre RD.`, `Il link è monouso e scade tra ${d.hours} ore. Se non sei stato tu, ignora questo messaggio.`], cta: { label: "Collega la mia prenotazione", url: d.url } }),
    "booking.reminder": (d) => ({ subject: `Promemoria: ${d.service} — ${d.dates}`, title: "Promemoria della prenotazione", body: [`Ciao ${d.name}, ti ricordiamo la tua prenotazione con ${d.operator}.`], rows: bookRows("it", d), cta: { label: "Vedi la mia prenotazione", url: d.url } }),
    "booking.review_request": (d) => ({ subject: `Com'era ${d.service}?`, title: "Com'è andato il viaggio?", body: [`Ciao ${d.name}, grazie per aver viaggiato con ${d.operator}. La tua opinione su ${d.service} aiuta gli altri viaggiatori.`], cta: { label: "Lascia la mia recensione", url: d.url } }),
    "newsletter.confirm": (d) => ({ subject: "Conferma l'iscrizione a Descubre RD", title: "Conferma l'iscrizione", body: ["Ancora un passaggio per ricevere le novità di Descubre RD.", "Se non sei stato tu, ignora questa e-mail."], cta: { label: "Conferma l'iscrizione", url: d.url } }),
    "support.received": (d) => ({ subject: `Abbiamo ricevuto il tuo messaggio (${d.reference})`, title: "Abbiamo ricevuto il tuo messaggio", body: [`Ciao ${d.name}, abbiamo ricevuto il tuo messaggio «${d.subject}».`, `Riferimento: ${d.reference}. Ti risponderemo il prima possibile.`] }),
    "establishment.received": (d) => ({ subject: `Richiesta ricevuta per ${d.establishment}`, title: "Richiesta ricevuta", body: [`Ciao ${d.name}, abbiamo ricevuto la richiesta di registrazione di ${d.establishment}. La esamineremo e ti aggiorneremo.`], cta: { label: "Vedi lo stato", url: d.url } }),
    "store.order_confirmation": (d) => ({ subject: `Ordine ${d.reference} confermato`, title: "Grazie per il tuo acquisto!", body: [`Ciao ${d.name}, abbiamo ricevuto il tuo ordine ${d.reference}.`], rows: [[L.it.items, d.items], [L.it.total, d.total], [L.it.order, d.reference]], cta: { label: "Vedi il mio ordine", url: d.url } }),
    "store.order_update": (d) => ({ subject: `${d.title} · ${d.reference}`, title: d.title, body: [`Ciao ${d.name}, ${d.message}`], rows: [[L.it.order, d.reference]], cta: { label: "Vedi il mio ordine", url: d.url } }),
  },
};

/** Convierte el texto declarativo en el correo completo (texto plano y HTML). Devuelve null si esa plantilla no está traducida a ese idioma. */
export function renderExtra<K extends TemplateKey>(key: K, locale: ExtraLocale, data: TemplateData[K], h: Helpers): (Rendered & { locale: ExtraLocale }) | null {
  if (key === "marketing.campaign") {
    const d = data as Data["marketing.campaign"];
    const l = L[locale];
    return { subject: d.subject, text: `${d.body}\n\n---\n${l.unsub}: ${d.unsubscribe_url}`, html: h.layout(d.subject, d.body.split(/\n{2,}/).map((x) => h.p(h.esc(x).replace(/\n/g, "<br>"))).join(""), undefined, `Descubre RD · ${l.unsub}: ${d.unsubscribe_url}`, locale), locale };
  }
  const build = (C[locale] as Record<string, ((d: unknown) => Copy) | undefined>)[key];
  if (!build) return null;
  const c = build(data);
  const text = [...c.body, ...(c.rows ?? []).map(([a, b]) => `${a}: ${b}`), ...(c.cta ? [`${c.cta.label}: ${c.cta.url}`] : [])].join("\n\n");
  const html = h.layout(c.title, c.body.map((x) => h.p(h.esc(x))).join("") + (c.rows ? h.table(c.rows) : ""), c.cta, c.footer ?? L[locale].footer, locale);
  return { subject: c.subject, text, html, locale };
}
