/**
 * Sitemap + robots.txt generator.
 *
 * Runs via `predev` / `prebuild` npm hooks. Parses static route paths
 * from src/App.tsx (skipping dynamic `:param` routes, wildcard `*`,
 * and private/admin routes) and writes public/sitemap.xml.
 *
 * Also emits public/robots.txt with the same Disallow list so the two
 * files stay in sync.
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const BASE_URL = "https://descubrerd.lovable.app";

// Routes that should never be indexed (auth, admin, private, utility).
const PRIVATE_PREFIXES = [
  "/admin",
  "/login",
  "/registro",
  "/reset-password",
  "/perfil",
  "/reservas",
  "/check-in",
  "/mi-viaje",
  "/mis-logros",
  "/perfil-jugador",
  "/pasaporte-digital",
];

function isPrivate(path: string): boolean {
  return PRIVATE_PREFIXES.some((p) => path === p || path.startsWith(p + "/"));
}

function extractRoutes(source: string): string[] {
  const routeRegex = /<Route\s+path="([^"]+)"/g;
  const routes = new Set<string>();
  let match: RegExpExecArray | null;
  while ((match = routeRegex.exec(source)) !== null) {
    const path = match[1];
    if (path === "*" || path.includes(":")) continue; // dynamic / catch-all
    if (isPrivate(path)) continue;
    routes.add(path);
  }
  return Array.from(routes).sort();
}

function priorityFor(path: string): string {
  if (path === "/") return "1.0";
  const depth = path.split("/").filter(Boolean).length;
  if (depth === 1) return "0.9";
  if (depth === 2) return "0.7";
  return "0.5";
}

function changefreqFor(path: string): string {
  if (path === "/") return "daily";
  if (path === "/blog" || path === "/eventos" || path === "/ofertas")
    return "daily";
  return "weekly";
}

function buildSitemap(paths: string[]): string {
  const lastmod = new Date().toISOString().slice(0, 10);
  const urls = paths
    .map(
      (p) =>
        `  <url>\n    <loc>${BASE_URL}${p}</loc>\n    <lastmod>${lastmod}</lastmod>\n    <changefreq>${changefreqFor(p)}</changefreq>\n    <priority>${priorityFor(p)}</priority>\n  </url>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

function buildRobots(): string {
  const disallow = PRIVATE_PREFIXES.map((p) => `Disallow: ${p}`).join("\n");
  return `# Auto-generated by scripts/generate-sitemap.ts — do not edit manually.
User-agent: Googlebot
Allow: /

User-agent: Bingbot
Allow: /

User-agent: Twitterbot
Allow: /

User-agent: facebookexternalhit
Allow: /

User-agent: *
Allow: /
${disallow}

Sitemap: ${BASE_URL}/sitemap.xml
`;
}

function main() {
  const appTsx = readFileSync(resolve("src/App.tsx"), "utf8");
  const routes = extractRoutes(appTsx);
  writeFileSync(resolve("public/sitemap.xml"), buildSitemap(routes));
  writeFileSync(resolve("public/robots.txt"), buildRobots());
  console.log(
    `[sitemap] wrote ${routes.length} entries → public/sitemap.xml + robots.txt`,
  );
}

main();