
-- Seed restaurants (skip existing)
INSERT INTO public.restaurants (name, slug, category, cuisine_type, description, short_description, image_url, address, phone, email, website, price_range, opening_hours, rating, review_count, services, signature_dishes, is_featured, is_active, latitude, longitude)
VALUES
('Meson de Bari', 'meson-de-bari', 'local', 'Dominicana', 'El Mesón de Bari es un templo de la gastronomía dominicana tradicional. Desde 1956, este restaurante familiar ha servido los platos más auténticos de la cocina criolla.', 'Cocina criolla dominicana auténtica desde 1956.', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800', 'Av. Hostos 302, Zona Colonial, Santo Domingo', '+1 809-687-4091', NULL, NULL, '$$', 'Lun-Dom 7:00 AM - 10:00 PM', 4.5, 1540, ARRAY['Comida para llevar', 'Delivery', 'WiFi', 'Grupos grandes'], ARRAY['La Bandera Dominicana', 'Mofongo Relleno', 'Chivo Guisado', 'Sancocho de 7 Carnes'], true, true, 18.4720, -69.8870),
('La Yola', 'la-yola', 'seafood', 'Mariscos Mediterránea', 'Situado sobre el mar en la Marina de Cap Cana, La Yola ofrece mariscos frescos y cocina mediterránea en un ambiente mágico.', 'Mariscos frescos sobre el mar Caribe en Cap Cana.', 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800', 'Marina Cap Cana, Punta Cana', '+1 809-227-2262', 'reservas@layola.do', 'https://layola.do', '$$$$', 'Lun-Dom 12:00 PM - 11:00 PM', 4.8, 673, ARRAY['Vista al mar', 'Reservaciones obligatorias', 'Carta de vinos premium', 'Valet parking'], ARRAY['Langosta a la Parrilla', 'Ceviche de Camarón', 'Paella Marinera', 'Atún Sellado'], true, true, 18.4620, -68.3940),
('Peperoni', 'peperoni-ristorante', 'casual', 'Italiana', 'Peperoni es el restaurante italiano más querido de Santo Domingo con pizzas artesanales de horno de leña.', 'Auténtica cocina italiana con pizzas artesanales en Santo Domingo.', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800', 'Av. Roberto Pastoriza 226, Naco, Santo Domingo', '+1 809-562-5057', NULL, 'https://peperoni.com.do', '$$', 'Lun-Dom 12:00 PM - 12:00 AM', 4.4, 2100, ARRAY['Delivery', 'Terraza', 'WiFi', 'Para niños'], ARRAY['Pizza Peperoni Especial', 'Pasta Carbonara', 'Lasagna de la Casa'], false, true, 18.4650, -69.9200),
('Boca Marina', 'boca-marina', 'seafood', 'Mariscos Dominicana', 'Icónico restaurante de mariscos frente al mar en Boca Chica con décadas de tradición.', 'Mariscos frescos frente al mar en Boca Chica.', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800', 'Playa Boca Chica, San Pedro de Macorís', '+1 809-523-4303', NULL, NULL, '$$', 'Lun-Dom 10:00 AM - 10:00 PM', 4.3, 980, ARRAY['Frente al mar', 'Grupos grandes', 'Música en vivo'], ARRAY['Langosta Boca Marina', 'Pescado Frito al Coco', 'Camarones al Ajillo'], false, true, 18.4500, -69.6100)
ON CONFLICT (slug) DO NOTHING;

-- Seed hotels (skip existing)
INSERT INTO public.hotels (name, slug, category, description, short_description, image_url, address, phone, email, website, price_range, stars, rating, review_count, amenities, is_featured, is_active, latitude, longitude)
VALUES
('Tortuga Bay', 'tortuga-bay', 'boutique', 'Hotel boutique diseñado por Oscar de la Renta con playa privada y servicio de mayordomo en Punta Cana.', 'Hotel boutique diseñado por Oscar de la Renta en Punta Cana.', 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800', 'Puntacana Resort & Club, Punta Cana', '+1 809-959-2262', 'reservas@tortugabay.com', 'https://tortugabay.puntacana.com', '$$$$', 5, 4.9, 456, ARRAY['Playa privada', 'Spa', 'Golf', 'Butler service', 'Piscina infinita', 'WiFi', 'Transfer aeropuerto'], true, true, 18.5100, -68.3680),
('Casa Colonial Beach & Spa', 'casa-colonial', 'boutique', 'Resort boutique colonial de cinco estrellas frente a la playa en Puerto Plata.', 'Resort boutique colonial en Puerto Plata.', 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', 'Playa Dorada, Puerto Plata', '+1 809-320-3232', 'info@casacolonial.com', 'https://casacolonial.com', '$$$', 5, 4.7, 678, ARRAY['Spa', 'Playa privada', 'Restaurante gourmet', 'Piscina', 'WiFi', 'Gimnasio'], true, true, 19.7800, -70.6900),
('Sublime Samana', 'sublime-samana', 'boutique', 'Resort eco-chic con villas de piscina privada en la península de Samaná.', 'Resort eco-chic en Samaná.', 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', 'Carretera Las Terrenas-El Limón, Samaná', '+1 809-240-5555', 'reservations@sublimesamana.com', 'https://sublimesamana.com', '$$$', 5, 4.8, 342, ARRAY['Piscinas privadas', 'Spa orgánico', 'Yoga', 'Restaurante farm-to-table', 'WiFi', 'Bicicletas'], true, true, 19.3100, -69.5400),
('Zoëtry Agua Punta Cana', 'zoetry-agua', 'all-inclusive', 'Resort all-inclusive de lujo boutique con enfoque en bienestar en Punta Cana.', 'All-inclusive boutique de bienestar en Punta Cana.', 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800', 'Playa Uvero Alto, Punta Cana', '+1 809-468-0000', 'info@zoetryagua.com', 'https://zoetryresorts.com', '$$$$', 5, 4.6, 890, ARRAY['Todo incluido', 'Spa', 'Yoga', 'Snorkel', 'Kayak', 'WiFi', 'Restaurantes gourmet'], false, true, 18.7200, -68.5100)
ON CONFLICT (slug) DO NOTHING;

-- Seed experiences (skip existing)
INSERT INTO public.experiences (name, slug, category, experience_type, description, short_description, image_url, duration, difficulty, price_range, best_season, included, requirements, highlights, rating, review_count, is_featured, is_active)
VALUES
('Canyoning en Damajagua', 'canyoning-damajagua', 'aventura', 'outdoor', 'Descubre las 27 cascadas de Damajagua en una aventura de canyoning única.', 'Salta y deslízate por las 27 cascadas de Damajagua.', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800', '4-5 horas', 'moderado', '$$', 'Todo el año', ARRAY['Guía certificado', 'Equipo de seguridad', 'Transporte'], ARRAY['Saber nadar', 'Buena condición física'], ARRAY['27 cascadas naturales', 'Saltos de hasta 8 metros', 'Toboganes de roca', 'Selva tropical'], 4.8, 1250, true, true),
('Tour Zona Colonial', 'tour-zona-colonial', 'cultural', 'walking-tour', 'Camina por las calles empedradas de la primera ciudad del Nuevo Mundo.', 'Recorrido histórico por la Zona Colonial de Santo Domingo.', 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800', '3 horas', 'fácil', '$', 'Todo el año', ARRAY['Guía historiador', 'Entrada a monumentos', 'Degustación de chocolate'], ARRAY['Calzado cómodo', 'Protección solar'], ARRAY['Catedral Primada de América', 'Alcázar de Colón', 'Fortaleza Ozama'], 4.6, 890, true, true),
('Kayak Bioluminiscente Laguna Gri-Gri', 'kayak-bioluminiscente', 'naturaleza', 'water', 'Navega en kayak bajo las estrellas por la mágica Laguna Gri-Gri donde el agua se ilumina.', 'Kayak nocturno en aguas bioluminiscentes.', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800', '2 horas', 'fácil', '$$', 'Abril - Noviembre', ARRAY['Kayak doble', 'Guía nocturno', 'Chaleco salvavidas'], ARRAY['Saber nadar'], ARRAY['Bioluminiscencia natural', 'Cielo estrellado', 'Manglares'], 4.9, 340, true, true)
ON CONFLICT (slug) DO NOTHING;

-- Seed bars (skip existing)
INSERT INTO public.bars (name, slug, bar_type, ambiance, music_style, description, short_description, image_url, address, phone, price_range, opening_hours, dress_code, services, rating, review_count, is_featured, is_active)
VALUES
('Onno''s Bar', 'onnos-bar', 'beach-bar', 'Tropical relajado', 'Reggae, Electrónica', 'Bar de playa icónico en Cabarete con DJ sets al atardecer y cócteles artesanales.', 'Bar de playa icónico en Cabarete.', 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800', 'Playa Cabarete, Puerto Plata', '+1 809-571-0461', '$$', 'Lun-Dom 10:00 AM - 2:00 AM', 'Casual', ARRAY['DJ en vivo', 'Cócteles artesanales', 'Comida de playa', 'WiFi'], 4.6, 780, true, true),
('La Cassina Wine Bar', 'la-cassina-wine', 'wine-bar', 'Elegante íntimo', 'Jazz, Bossa Nova', 'Wine bar sofisticado con 200+ etiquetas en la Zona Colonial de Santo Domingo.', 'Wine bar sofisticado en la Zona Colonial.', 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800', 'Calle Hostos 163, Zona Colonial, Santo Domingo', '+1 809-333-8271', '$$$', 'Mar-Dom 5:00 PM - 12:00 AM', 'Smart Casual', ARRAY['Carta de vinos premium', 'Tapas gourmet', 'Terraza colonial', 'Catas privadas'], 4.8, 420, true, true)
ON CONFLICT (slug) DO NOTHING;
