
ALTER TABLE public.ad_banners
  ADD COLUMN IF NOT EXISTS content_type TEXT NOT NULL DEFAULT 'image',
  ADD COLUMN IF NOT EXISTS video_url TEXT,
  ADD COLUMN IF NOT EXISTS video_autoplay BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS video_loop BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS video_muted BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS animation_type TEXT,
  ADD COLUMN IF NOT EXISTS animation_config JSONB,
  ADD COLUMN IF NOT EXISTS slider_items JSONB,
  ADD COLUMN IF NOT EXISTS slider_interval INTEGER DEFAULT 5000;
