-- Seed more restaurants for key destinations
INSERT INTO public.restaurants (name, slug, category, cuisine_type, description, short_description, image_url, address, price_range, rating, review_count, is_featured, is_active)
VALUES
  ('Mesón de Bari', 'meson-de-bari', 'fine-dining', 'Dominicana', 'Ubicado en la Zona Colonial, ofrece cocina dominicana gourmet con ingredientes locales de primera calidad en un ambiente colonial único.', 'Cocina dominicana gourmet en la Zona Colonial', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600', 'Calle Hostos 302, Zona Colonial, Santo Domingo', '$$$', 4.7, 320, true, true),
  ('La Cassina', 'la-cassina', 'fine-dining', 'Italiana-Dominicana', 'Fusión ítalo-dominicana en un palacete del siglo XVI completamente restaurado. Pasta artesanal y mariscos del Caribe.', 'Fusión italiana en palacete colonial', 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=600', 'Calle Arzobispo Meriño, Zona Colonial', '$$$$', 4.8, 245, true, true),
  ('El Conuco', 'el-conuco', 'traditional', 'Dominicana Tradicional', 'Experiencia gastronómica tradicional con show en vivo de folclore dominicano. Platos típicos como mangú, sancocho y mofongo.', 'Cocina típica con show folclórico', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600', 'Calle Casimiro de Moya 152, Santo Domingo', '$$', 4.5, 890, true, true),
  ('Jellyfish Restaurant', 'jellyfish-restaurant', 'beach-dining', 'Mediterránea-Caribeña', 'Restaurante frente al mar en Bávaro con los pies en la arena. Especialidad en mariscos frescos y cócteles tropicales.', 'Gastronomía frente al mar en Bávaro', 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=600', 'Playa Bávaro, Punta Cana', '$$$', 4.6, 567, true, true),
  ('The Beach Club by Le Cirque', 'beach-club-le-cirque', 'fine-dining', 'Internacional', 'Extensión caribeña del icónico Le Cirque de Nueva York. Alta cocina internacional con vista panorámica al mar.', 'Alta cocina internacional en Cap Cana', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600', 'Cap Cana, Punta Cana', '$$$$', 4.9, 189, true, true),
  ('El Pescador', 'el-pescador-samana', 'seafood', 'Mariscos', 'Pescado y mariscos recién sacados del mar. Ambiente rústico-caribeño con terraza sobre el agua en la bahía de Samaná.', 'Mariscos frescos en la bahía de Samaná', 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?w=600', 'Malecón de Samaná', '$$', 4.7, 432, true, true),
  ('Kaffe Café', 'kaffe-cafe-jarabacoa', 'cafe', 'Café de Especialidad', 'Café de altura cultivado localmente en Jarabacoa. Tostado artesanal, repostería casera y desayunos con productos de la montaña.', 'Café de montaña y repostería artesanal', 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600', 'Calle Principal, Jarabacoa', '$', 4.8, 298, true, true)
ON CONFLICT DO NOTHING;

-- Seed more hotels
INSERT INTO public.hotels (name, slug, category, description, short_description, image_url, address, price_range, rating, review_count, stars, is_featured, is_active)
VALUES
  ('Sanctuary Cap Cana', 'sanctuary-cap-cana', 'resort', 'Resort de lujo solo para adultos en Cap Cana con servicio de mayordomo, playa privada y campo de golf de campeonato.', 'Resort exclusivo adults-only en Cap Cana', 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600', 'Boulevard Cap Cana, Punta Cana', '$$$$', 4.9, 1250, 5, true, true),
  ('Amanera', 'amanera-playa-grande', 'boutique', 'Resort boutique ultra-exclusivo de la cadena Aman en los acantilados de Playa Grande. Villas privadas con piscina y vistas al Atlántico.', 'Resort Aman en acantilados de Playa Grande', 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600', 'Playa Grande, Río San Juan', '$$$$$', 4.9, 89, 5, true, true),
  ('Casa Bonita Tropical Lodge', 'casa-bonita-barahona', 'eco-lodge', 'Eco-lodge de lujo suspendido entre la montaña y el mar en Barahona. Piscinas de borde infinito y gastronomía orgánica.', 'Eco-lodge de lujo entre montaña y mar', 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600', 'Km 17 Carretera de la Costa, Barahona', '$$$', 4.8, 445, 4, true, true),
  ('Tortuga Bay Puntacana', 'tortuga-bay-puntacana', 'resort', 'Resort de la colección Oscar de la Renta con villas diseñadas por el maestro dominicano. Playa privada y servicio personalizado.', 'Villas de diseño Oscar de la Renta', 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600', 'Puntacana Resort & Club', '$$$$', 4.9, 678, 5, true, true),
  ('Sublime Samaná', 'sublime-samana', 'boutique', 'Hotel boutique de diseño contemporáneo con residencias privadas rodeadas de cocoteros en Las Terrenas.', 'Boutique hotel de diseño en Las Terrenas', 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600', 'Las Terrenas, Samaná', '$$$', 4.7, 356, 5, true, true)
ON CONFLICT DO NOTHING;