-- Add is_sponsored column to key monetization tables
ALTER TABLE public.hotels ADD COLUMN IF NOT EXISTS is_sponsored boolean DEFAULT false;
ALTER TABLE public.restaurants ADD COLUMN IF NOT EXISTS is_sponsored boolean DEFAULT false;
ALTER TABLE public.bars ADD COLUMN IF NOT EXISTS is_sponsored boolean DEFAULT false;
ALTER TABLE public.airbnb_listings ADD COLUMN IF NOT EXISTS is_sponsored boolean DEFAULT false;
ALTER TABLE public.spas_wellness ADD COLUMN IF NOT EXISTS is_sponsored boolean DEFAULT false;
ALTER TABLE public.experiences ADD COLUMN IF NOT EXISTS is_sponsored boolean DEFAULT false;

-- Seed spas_wellness data
INSERT INTO public.spas_wellness (name, slug, spa_type, description, short_description, image_url, address, price_range, rating, review_count, services, treatments, amenities, opening_hours, is_featured, is_active)
VALUES
  ('Six Senses Spa Punta Cana', 'six-senses-spa-punta-cana', 'resort-spa', 'Experiencia de bienestar holístico con vistas al mar Caribe. Tratamientos orgánicos, programa detox y terapias inspiradas en la naturaleza dominicana.', 'Bienestar holístico frente al mar Caribe', 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800', 'Punta Cana Resort & Club', '$$$', 4.9, 567, ARRAY['Masajes', 'Faciales', 'Yoga', 'Meditación', 'Hidroterapia'], ARRAY['Masaje con aceite de coco', 'Envoltura de chocolate dominicano', 'Facial de aloe vera'], ARRAY['Piscina infinity', 'Sauna', 'Jacuzzi', 'Sala de relajación'], '8:00 AM - 8:00 PM', true, true),
  ('Spa Sanctuary Santo Domingo', 'spa-sanctuary-santo-domingo', 'day-spa', 'Oasis urbano de tranquilidad en el corazón de la capital. Productos locales y técnicas innovadoras para el bienestar integral.', 'Oasis de bienestar en la capital', 'https://images.unsplash.com/photo-1540555700478-4be289fbec6b?w=800', 'Calle El Conde, Zona Colonial, Santo Domingo', '$$', 4.7, 324, ARRAY['Masajes terapéuticos', 'Tratamientos faciales', 'Manicure', 'Pedicure'], ARRAY['Masaje descontracturante', 'Facial rejuvenecedor', 'Exfoliación corporal'], ARRAY['Sala de vapor', 'Duchas sensoriales'], '9:00 AM - 7:00 PM', false, true),
  ('Casa de Campo Spa', 'casa-de-campo-spa', 'resort-spa', 'Spa de lujo con tratamientos exclusivos y vistas tropicales. Terapias de pareja, circuito de aguas y tratamientos con cacao dominicano.', 'Spa de lujo en Casa de Campo', 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800', 'Casa de Campo Resort, La Romana', '$$$$', 4.8, 456, ARRAY['Terapias de pareja', 'Circuito de aguas', 'Tratamientos corporales', 'Yoga'], ARRAY['Tratamiento de cacao dominicano', 'Masaje con piedras calientes', 'Envoltura tropical'], ARRAY['Piscinas termales', 'Sauna finlandesa', 'Baño turco', 'Jardín zen'], '7:00 AM - 9:00 PM', true, true),
  ('Jarabacoa Eco Spa', 'jarabacoa-eco-spa', 'eco-spa', 'Bienestar natural en las montañas con productos orgánicos locales. Masajes con aceites esenciales de la montaña y baños de flores silvestres.', 'Bienestar natural en la montaña', 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800', 'Carretera Jarabacoa-Constanza Km 5', '$', 4.6, 189, ARRAY['Masajes con aceites esenciales', 'Baños de flores', 'Aromaterapia', 'Meditación guiada'], ARRAY['Masaje con miel de montaña', 'Baño de flores silvestres', 'Reflexología'], ARRAY['Piscina natural', 'Senderos de meditación', 'Huerto orgánico'], '8:00 AM - 6:00 PM', false, true),
  ('Spa Eden Roc Cap Cana', 'spa-eden-roc-cap-cana', 'resort-spa', 'El spa más exclusivo de Cap Cana. Tratamientos de lujo con productos marinos y técnicas de hidroterapia avanzada frente al mar.', 'Spa ultra-exclusivo en Cap Cana', 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=800', 'Eden Roc Cap Cana, Punta Cana', '$$$$', 4.9, 234, ARRAY['Talasoterapia', 'Tratamientos anti-age', 'Circuito hidrotermal', 'Yoga sunrise'], ARRAY['Facial con perlas marinas', 'Masaje con arena volcánica', 'Envoltura de algas'], ARRAY['Piscina flotante', 'Cabanas privadas', 'Bar de jugos detox'], '6:00 AM - 10:00 PM', true, true)
ON CONFLICT DO NOTHING;